# Dataset Final v2 — Features complètes
- Komoot surfaces (0 pour colonnes vides si URL présente, NaN si pas d'URL)
- Features GPX : distance, dénivelé, cols, gradient fin de course
- Nouvelles features : profil début de course (50 premiers km)
- Liste des courses sans données Komoot

In [1]:
import os
import re
import numpy as np
import pandas as pd
import gpxpy
from scipy.signal import find_peaks
from tqdm import tqdm

BASE       = '/Users/arthurdeletang/Desktop/Stage M1/Code/data'
GPX_DIR    = os.path.join(BASE, 'gpx_files_2')
MATCH_DIR  = os.path.join(BASE, 'matching', 'all')
KOMOOT_CSV = os.path.join(MATCH_DIR, 'komoot_surface_all.csv')
OUTPUT_CSV = os.path.join(MATCH_DIR, 'dataset_final_v2.csv')

/Users/arthurdeletang/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
# ── 1. Charger tous les fichiers matching ─────────────────────────────────────
dfs = []
for year in range(2017, 2026):
    path = os.path.join(MATCH_DIR, f'matching_{year}.csv')
    if os.path.exists(path):
        df = pd.read_csv(path)
        df = df[df['statut'] == 'match']
        dfs.append(df)
        print(f'{year} : {len(df)} courses')

df_match = pd.concat(dfs, ignore_index=True)
df_match = df_match.drop_duplicates(subset='fichier_gpx')
print(f'Total unique : {len(df_match)} courses')

2017 : 595 courses
2018 : 1040 courses
2019 : 1062 courses
2020 : 448 courses
2021 : 700 courses
2022 : 813 courses
2023 : 937 courses
2024 : 890 courses
2025 : 906 courses
Total unique : 7391 courses

In [3]:
# ── 2. Joindre avec Komoot ────────────────────────────────────────────────────
df_komoot = pd.read_csv(KOMOOT_CSV)
if '_km' in df_komoot.columns:
    df_komoot = df_komoot.drop(columns=['_km'])

cols_komoot = [c for c in df_komoot.columns if c not in ['fichier_gpx', 'route_url']]
print(f'Komoot : {len(df_komoot)} lignes, {len(cols_komoot)} colonnes surface')

df = df_match.merge(df_komoot, on='fichier_gpx', how='left')

# Pour les courses AVEC URL Komoot : remplacer NaN des colonnes surface par 0
# Pour les courses SANS URL Komoot : laisser NaN
mask_avec_url = df['route_url'].notna()
df.loc[mask_avec_url, cols_komoot] = df.loc[mask_avec_url, cols_komoot].fillna(0)

print(f'Avec URL Komoot : {mask_avec_url.sum()}')
print(f'Sans URL Komoot : {(~mask_avec_url).sum()}')

Komoot : 7343 lignes, 17 colonnes surface
Avec URL Komoot : 7217
Sans URL Komoot : 174

In [4]:
# ── 3. Courses sans données Komoot ────────────────────────────────────────────
sans_komoot = df[df['route_url'].isna()][['fichier_gpx', 'annee', 'categorie', 'nom_pcs']]
print(f'Courses sans Komoot : {len(sans_komoot)}')
print(sans_komoot['annee'].value_counts().sort_index())
print('\nListe complète :')
pd.set_option('display.max_rows', None)
print(sans_komoot.to_string(index=False))

Courses sans Komoot : 174
annee
2017    12
2018    28
2019    21
2020     5
2021    18
2022    23
2023    23
2024    25
2025    19
Name: count, dtype: int64

Liste complète :
                                                             fichier_gpx  annee categorie                                            nom_pcs
                   2017 Dwars Door Vlaanderen - A travers la Flandre.gpx   2017     1.UWT                              dwars-door-vlaanderen
                                       2017 Tour of Thailand Stage 2.gpx   2017       2.1                                   tour-of-thailand
       2017 GP de Denain - Porte du Hainaut - Valenciennes Metropole.gpx   2017      1.HC                                       gp-de-denain
  2017 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 1.gpx   2017      2.HC                               4-jours-de-dunkerque
  2017 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 2.gpx   2017      2.HC                               4-jours-de-dunkerque
  2017 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 3.gpx   2017      2.HC                               4-jours-de-dunkerque
  2017 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 4.gpx   2017      2.HC                               4-jours-de-dunkerque
  2017 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 5.gpx   2017      2.HC                               4-jours-de-dunkerque
  2017 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 6.gpx   2017      2.HC                               4-jours-de-dunkerque
              2017 Grand Prix de la Somme - Conseil Departemental 80.gpx   2017       1.1                                     gp-de-la-somme
                                     2017 Koga Slag om Norg Rest day.gpx   2017       1.1                                       slag-om-norg
                               2017 GP de Fourmies - La Voix du Nord.gpx   2017      1.HC                                     gp-de-fourmies
                   2018 Dwars Door Vlaanderen - A travers la Flandre.gpx   2018     1.UWT                              dwars-door-vlaanderen
  2018 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 1.gpx   2018      2.HC                               4-jours-de-dunkerque
  2018 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 2.gpx   2018      2.HC                               4-jours-de-dunkerque
  2018 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 3.gpx   2018      2.HC                               4-jours-de-dunkerque
  2018 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 4.gpx   2018      2.HC                               4-jours-de-dunkerque
  2018 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 5.gpx   2018      2.HC                               4-jours-de-dunkerque
  2018 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 6.gpx   2018      2.HC                               4-jours-de-dunkerque
2018 A Travers les Hauts de France - Trophe Paris-Arras Tour Stage 1.gpx   2018       2.2                                   paris-arras-tour
2018 A Travers les Hauts de France - Trophe Paris-Arras Tour Stage 2.gpx   2018       2.2                                   paris-arras-tour
2018 A Travers les Hauts de France - Trophe Paris-Arras Tour Stage 3.gpx   2018       2.2                                   paris-arras-tour
 2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 1.gpx   2018       2.1                              adriatica-ionica-race
 2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 2.gpx   2018       2.1                              adriatica-ionica-race
 2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 3.gpx   2018       2.1                              adriatica-ionica-race
 2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 4.gpx   2018       2.1                              adriatica-ionica-race
 2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 5.gpx   2018       2.1                              adriatica-ionica-race
                                   2018 White Spot - Delta Road Race.gpx   2018       1.2                                      tour-de-delta
                               2018 GP de Fourmies - La Voix du Nord.gpx   2018      1.HC                                     gp-de-fourmies
             2018 Okolo jiznich Cech - Tour of South Bohemia Stage 1.gpx   2018       2.2                                 okolo-jiznich-cech
             2018 Okolo jiznich Cech - Tour of South Bohemia Stage 2.gpx   2018       2.2                                 okolo-jiznich-cech
             2018 Okolo jiznich Cech - Tour of South Bohemia Stage 3.gpx   2018       2.2                                 okolo-jiznich-cech
             2018 Okolo jiznich Cech - Tour of South Bohemia Stage 4.gpx   2018       2.2                                 okolo-jiznich-cech
             2018 Okolo jiznich Cech - Tour of South Bohemia Stage 5.gpx   2018       2.2                                 okolo-jiznich-cech
                                           2018 Tour de Siak Stage 1.gpx   2018       2.2                                       tour-de-siak
                                         2018 Tour of Almaty Stage 1.gpx   2018       2.1                                     tour-of-almaty
                                         2018 Tour of Fuzhou Stage 4.gpx   2018       2.1                                     tour-of-fuzhou
                                               2018 Africa Cup - TTT.gpx   2018       1.2                                     africa-cup-ttt
                                               2018 Africa Cup - ITT.gpx   2018       1.2                                     africa-cup-itt
                                                     2018 Africa Cup.gpx   2018       1.1                                         africa-cup
                   2019 COPACI Campeonato Panamericano de Ruta - ITT.gpx   2019        CC                              panamerican-champ-itt
              2019 Grand Prix de la Somme - Conseil Departemental 80.gpx   2019       1.2                                     gp-de-la-somme
  2019 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 1.gpx   2019      2.HC                               4-jours-de-dunkerque
  2019 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 2.gpx   2019      2.HC                               4-jours-de-dunkerque
  2019 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 3.gpx   2019      2.HC                               4-jours-de-dunkerque
  2019 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 4.gpx   2019      2.HC                               4-jours-de-dunkerque
  2019 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 5.gpx   2019      2.HC                               4-jours-de-dunkerque
  2019 4 Jours de Dunkerque - Grand Prix des Hauts-de-France Stage 6.gpx   2019      2.HC                               4-jours-de-dunkerque
2019 A Travers les Hauts de France - Trophe Paris-Arras Tour Stage 1.gpx   2019       2.2                                   paris-arras-tour
2019 A Travers les Hauts de France - Trophe Paris-Arras Tour Stage 2.gpx   2019       2.2                                   paris-arras-tour
2019 A Travers les Hauts de France - Trophe Paris-Arras Tour Stage 3.gpx   2019       2.2                                   paris-arras-tour
                          2019 Dominican Road National Championships.gpx   2019        NC                              nc-dominican-republic
                           2019 Georgian Road National Championships.gpx   2019        NC                                         nc-georgia
                                   2019 White Spot - Delta Road Race.gpx   2019       1.2                                      tour-de-delta
                                             2019 Gran Premio Chapin.gpx   2019       1.2                                 gran-premio-chapin
  2019 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 1.gpx   2019       2.1                              adriatica-ionica-race
  2019 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 2.gpx   2019       2.1                              adriatica-ionica-race
  2019 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 3.gpx   2019       2.1                              adriatica-ionica-race
  2019 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 4.gpx   2019       2.1                              adriatica-ionica-race
                            2019 Chinese Road National Championships.gpx   2019        NC                                           nc-china
                               2019 GP de Fourmies - La Voix du Nord.gpx   2019      1.HC                                     gp-de-fourmies
                    2020 Ukrainian Road National Championships - ITT.gpx   2020        NC                                     nc-ukraine-itt
                                2020 Antwerp Port Epic - Sels Trophy.gpx   2020       1.1                                  antwerp-port-epic
                            2020 Chinese Road National Championships.gpx   2020        NC                                           nc-china
                2020 Elite Road Central American Championships - ITT.gpx   2020       1.2      elite-road-central-american-championships-itt
                      2020 Elite Road Central American Championships.gpx   2020       1.2 elite-road-central-american-championships-road-rac
                                              2021 Ronde van Limburg.gpx   2021       1.1                                  ronde-van-limburg
  2021 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 1.gpx   2021       2.1                              adriatica-ionica-race
  2021 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 2.gpx   2021       2.1                              adriatica-ionica-race
  2021 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 3.gpx   2021       2.1                              adriatica-ionica-race
                      2021 Elite Road Central American Championships.gpx   2021       1.2 elite-road-central-american-championships-road-rac
             2021 Okolo jiznich Cech - Tour of South Bohemia Stage 1.gpx   2021       2.2                                 okolo-jiznich-cech
             2021 Okolo jiznich Cech - Tour of South Bohemia Stage 2.gpx   2021       2.2                                 okolo-jiznich-cech
             2021 Okolo jiznich Cech - Tour of South Bohemia Stage 3.gpx   2021       2.2                                 okolo-jiznich-cech
             2021 Okolo jiznich Cech - Tour of South Bohemia Stage 4.gpx   2021       2.2                                 okolo-jiznich-cech
                                2021 Antwerp Port Epic - Sels Trophy.gpx   2021       1.1                                  antwerp-port-epic
                               2021 GP de Fourmies - La Voix du Nord.gpx   2021     1.Pro                                     gp-de-fourmies
                   2021 Okolo Slovenska - Tour de Slovaquie Prologue.gpx   2021       2.1                                    okolo-slovenska
                    2021 Okolo Slovenska - Tour de Slovaquie Stage 1.gpx   2021       2.1                                    okolo-slovenska
                    2021 Okolo Slovenska - Tour de Slovaquie Stage 2.gpx   2021       2.1                                    okolo-slovenska
                    2021 Okolo Slovenska - Tour de Slovaquie Stage 3.gpx   2021       2.1                                    okolo-slovenska
                    2021 Okolo Slovenska - Tour de Slovaquie Stage 4.gpx   2021       2.1                                    okolo-slovenska
        2021 Binche - Chimay - Binche - Memorial Frank Vandenbroucke.gpx   2021       1.1                       memorial-frank-vandenbroucke
                                     2021 61th Craft Ster van Zwolle.gpx   2021       1.2                                    ster-van-zwolle
                           2022 CAC African Road Championships - TTT.gpx   2022        CC                  african-cycling-championships-ttt
                           2022 CAC African Road Championships - ITT.gpx   2022        CC              african-continental-championships-itt
                   2022 Dwars door Vlaanderen - A travers la Flandre.gpx   2022     1.UWT                              dwars-door-vlaanderen
  2022 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 1.gpx   2022     2.Pro                               4-jours-de-dunkerque
  2022 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 2.gpx   2022     2.Pro                               4-jours-de-dunkerque
  2022 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 3.gpx   2022     2.Pro                               4-jours-de-dunkerque
  2022 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 4.gpx   2022     2.Pro                               4-jours-de-dunkerque
  2022 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 5.gpx   2022     2.Pro                               4-jours-de-dunkerque
  2022 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 6.gpx   2022     2.Pro                               4-jours-de-dunkerque
                                2022 Antwerp Port Epic - Sels Trophy.gpx   2022       1.1                                  antwerp-port-epic
  2022 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 1.gpx   2022       2.1                              adriatica-ionica-race
  2022 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 2.gpx   2022       2.1                              adriatica-ionica-race
  2022 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 3.gpx   2022       2.1                              adriatica-ionica-race
  2022 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 4.gpx   2022       2.1                              adriatica-ionica-race
  2022 Adriatica Ionica Race - Sulle Rotte della Serenissima Stage 5.gpx   2022       2.1                              adriatica-ionica-race
                     2022 Schaal Sels Merksem/ Johan Museeuw Classic.gpx   2022       1.1                                      schaal-schels
            2022 Okolo jiznich Cech - Tour of South Bohemia Prologue.gpx   2022       2.2                                 okolo-jiznich-cech
             2022 Okolo jiznich Cech - Tour of South Bohemia Stage 1.gpx   2022       2.2                                 okolo-jiznich-cech
             2022 Okolo jiznich Cech - Tour of South Bohemia Stage 2.gpx   2022       2.2                                 okolo-jiznich-cech
             2022 Okolo jiznich Cech - Tour of South Bohemia Stage 3.gpx   2022       2.2                                 okolo-jiznich-cech
                               2022 GP de Fourmies - La Voix du Nord.gpx   2022     1.Pro                                     gp-de-fourmies
                  2022 Memorial Rik Van Steenbergen - Kempen Classic.gpx   2022       1.1                       memorial-rik-van-steenbergen
                             2022 Vuelta Ciclista al Ecuador Stage 8.gpx   2022       2.2                                   vuelta-a-ecuador
                             2023 GP Vorarlberg p/b RadHaus Rankweil.gpx   2023       1.2                                      gp-vorarlberg
  2023 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 1.gpx   2023     2.Pro                               4-jours-de-dunkerque
  2023 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 2.gpx   2023     2.Pro                               4-jours-de-dunkerque
  2023 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 3.gpx   2023     2.Pro                               4-jours-de-dunkerque
  2023 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 4.gpx   2023     2.Pro                               4-jours-de-dunkerque
  2023 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 5.gpx   2023     2.Pro                               4-jours-de-dunkerque
                                2023 Antwerp Port Epic - Sels Trophy.gpx   2023       1.1                                  antwerp-port-epic
  2023 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 6.gpx   2023     2.Pro                               4-jours-de-dunkerque
                            2023 Canadian Road National Championship.gpx   2023        NC                                         nc-canada2
               2023 Okolo jiznich Cech/Tour of South Bohemia Stage 1.gpx   2023       2.2                                 okolo-jiznich-cech
               2023 Okolo jiznich Cech/Tour of South Bohemia Stage 2.gpx   2023       2.2                                 okolo-jiznich-cech
               2023 Okolo jiznich Cech/Tour of South Bohemia Stage 3.gpx   2023       2.2                                 okolo-jiznich-cech
                                            2023 Grand Prix El Marsa.gpx   2023       1.2                                grand-prix-el-marsa
                               2023 GP de Fourmies - La Voix du Nord.gpx   2023     1.Pro                                     gp-de-fourmies
               2023 Okolo jiznich Cech/Tour of South Bohemia Stage 4.gpx   2023       2.2                                 okolo-jiznich-cech
                    2023 Okolo Slovenska - Tour de Slovaquie Stage 1.gpx   2023       2.1                                    okolo-slovenska
                    2023 Okolo Slovenska - Tour de Slovaquie Stage 2.gpx   2023       2.1                                    okolo-slovenska
                    2023 Okolo Slovenska - Tour de Slovaquie Stage 3.gpx   2023       2.1                                    okolo-slovenska
                    2023 Okolo Slovenska - Tour de Slovaquie Stage 4.gpx   2023       2.1                                    okolo-slovenska
                                   2023 Ixina Gooikse Pijl P/B Lotto.gpx   2023       1.1                                       gooikse-pijl
                    2023 Okolo Slovenska - Tour de Slovaquie Stage 5.gpx   2023       2.1                                    okolo-slovenska
                           2023 Vuelta Ciclistica al Ecuador Stage 6.gpx   2023       2.2                                   vuelta-a-ecuador
        2023 Binche - Chimay - Binche - Memorial Frank Vandenbroucke.gpx   2023       1.1                       memorial-frank-vandenbroucke
                                           2024 Tour of Oman Stage 4.gpx   2024     2.Pro                                       tour-of-oman
                                           2024 Tour of Oman Stage 5.gpx   2024     2.Pro                                       tour-of-oman
                            2024 GP Vorarlberg b/by Radhaus Rankweil.gpx   2024       1.2                                      gp-vorarlberg
                                         2024 Vuelta Bantrab Stage 1.gpx   2024       2.2                                     vuelta-bantrab
  2024 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 1.gpx   2024     2.Pro                               4-jours-de-dunkerque
  2024 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 2.gpx   2024     2.Pro                               4-jours-de-dunkerque
  2024 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 3.gpx   2024     2.Pro                               4-jours-de-dunkerque
  2024 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 4.gpx   2024     2.Pro                               4-jours-de-dunkerque
  2024 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 5.gpx   2024     2.Pro                               4-jours-de-dunkerque

In [5]:
# ── 4. Fonctions extraction GPX ───────────────────────────────────────────────

def parse_gpx_safe(filepath):
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
    content = re.sub(r'&(?!amp;|lt;|gt;|quot;|apos;|#)', '&amp;', content)
    return gpxpy.parse(content)

def find_gpx_path(fname, gpx_dir):
    full_path = os.path.join(gpx_dir, fname)
    if os.path.exists(full_path):
        return full_path
    replaced = fname.replace(' / ', ' - ')
    if os.path.exists(os.path.join(gpx_dir, replaced)):
        return os.path.join(gpx_dir, replaced)
    base = fname.split(' / ')[0].strip()
    for candidate in [base + ' .gpx', base + '.gpx']:
        path = os.path.join(gpx_dir, candidate)
        if os.path.exists(path):
            return path
    return None

def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    dlat, dlon = np.radians(lat2-lat1), np.radians(lon2-lon1)
    a = np.sin(dlat/2)**2 + np.cos(np.radians(lat1)) * np.cos(np.radians(lat2)) * np.sin(dlon/2)**2
    return R * 2 * np.arcsin(np.sqrt(a))

def get_number_peaks(series, prominence):
    store = find_peaks(series, prominence=prominence)
    try:
        if (len(store[0]) > 1) and (np.min(np.diff(store[0])) < prominence):
            return len(store[1]['prominences'][np.diff(np.insert(store[0], 0, 0)) > prominence])
        else:
            return len(store[1]['prominences'])
    except:
        return len(store[1]['prominences'])

def gradient_last_km(lats, lons, elevations, km):
    dist_cumul = 0.0
    for i in range(len(lats)-1, 0, -1):
        dist_cumul += haversine(lats[i-1], lons[i-1], lats[i], lons[i])
        if dist_cumul >= km:
            deniv = elevations[-1] - elevations[i-1]
            return round(deniv / (km * 1000) * 100, 2)
    total_dist = sum(haversine(lats[i], lons[i], lats[i+1], lons[i+1]) for i in range(len(lats)-1))
    if total_dist == 0:
        return 0.0
    return round((elevations[-1] - elevations[0]) / (total_dist * 1000) * 100, 2)

def gradient_first_km(lats, lons, elevations, km):
    """Gradient moyen sur les X premiers km."""
    dist_cumul = 0.0
    for i in range(len(lats)-1):
        dist_cumul += haversine(lats[i], lons[i], lats[i+1], lons[i+1])
        if dist_cumul >= km:
            deniv = elevations[i+1] - elevations[0]
            return round(deniv / (km * 1000) * 100, 2)
    # Trace plus courte que X km
    total_dist = sum(haversine(lats[i], lons[i], lats[i+1], lons[i+1]) for i in range(len(lats)-1))
    if total_dist == 0:
        return 0.0
    return round((elevations[-1] - elevations[0]) / (total_dist * 1000) * 100, 2)

def denivele_first_km(lats, lons, elevations, km):
    """Denivele positif sur les X premiers km."""
    dist_cumul = 0.0
    deniv = 0.0
    for i in range(len(lats)-1):
        dist_cumul += haversine(lats[i], lons[i], lats[i+1], lons[i+1])
        diff = elevations[i+1] - elevations[i]
        if diff > 0:
            deniv += diff
        if dist_cumul >= km:
            break
    return round(deniv, 0)

def extract_gpx_features(filepath):
    try:
        gpx = parse_gpx_safe(filepath)
        points = gpx.tracks[0].segments[0].points
        elevations = [p.elevation or 0 for p in points]
        lats = [p.latitude for p in points]
        lons = [p.longitude for p in points]

        dist = sum(haversine(lats[i], lons[i], lats[i+1], lons[i+1]) for i in range(len(lats)-1))
        elev_diff = np.diff(elevations)
        denivele_pos = float(np.sum(elev_diff[elev_diff > 0]))
        denivele_neg = float(np.abs(np.sum(elev_diff[elev_diff < 0])))
        max_elev = float(np.max(elevations))
        min_elev = float(np.min(elevations))

        elev_series = elevations + [0]
        n = len(elev_series)

        def loc_last(prominence):
            peaks = find_peaks(elev_series, prominence=prominence)[0]
            return float(np.max(peaks) / n) if len(peaks) > 0 else 0.0

        last_points = min(500, len(elevations))
        deniv_last_5km = float(np.sum(d for d in np.diff(elevations[-last_points:]) if d > 0))

        return {
            'distance_gpx_km':      round(dist, 2),
            'denivele_pos':         round(denivele_pos, 0),
            'denivele_neg':         round(denivele_neg, 0),
            'altitude_max':         round(max_elev, 0),
            'altitude_min':         round(min_elev, 0),
            'n_cols_hc':  get_number_peaks(elev_series, 800),
            'n_cols_cat1': get_number_peaks(elev_series, 640) - get_number_peaks(elev_series, 800),
            'n_cols_cat2': get_number_peaks(elev_series, 320) - get_number_peaks(elev_series, 640),
            'n_cols_cat3': get_number_peaks(elev_series, 160) - get_number_peaks(elev_series, 320),
            'n_cols_cat4': get_number_peaks(elev_series, 80)  - get_number_peaks(elev_series, 160),
            'loc_last_col_cat4':    round(loc_last(80), 4),
            'loc_last_col_cat3':    round(loc_last(160), 4),
            'loc_last_col_cat2':    round(loc_last(320), 4),
            'loc_last_col_cat1':    round(loc_last(640), 4),
            'loc_last_col_hc':      round(loc_last(800), 4),
            'gradient_last_1km':    gradient_last_km(lats, lons, elevations, 1),
            'gradient_last_3km':    gradient_last_km(lats, lons, elevations, 3),
            'gradient_last_5km':    gradient_last_km(lats, lons, elevations, 5),
            'denivele_last_5km':    round(deniv_last_5km, 0),
            # Nouvelles features debut de course
            'gradient_first_10km':  gradient_first_km(lats, lons, elevations, 10),
            'gradient_first_20km':  gradient_first_km(lats, lons, elevations, 20),
            'gradient_first_50km':  gradient_first_km(lats, lons, elevations, 50),
            'denivele_first_10km':  denivele_first_km(lats, lons, elevations, 10),
            'denivele_first_20km':  denivele_first_km(lats, lons, elevations, 20),
            'denivele_first_50km':  denivele_first_km(lats, lons, elevations, 50),
        }
    except Exception as e:
        print(f'  Erreur {os.path.basename(filepath)} : {e}')
        return {}

print('Fonctions chargees.')

Fonctions chargees.

In [6]:
# ── 5. Extraction GPX ─────────────────────────────────────────────────────────
gpx_features = []
for fname in tqdm(df['fichier_gpx']):
    if pd.isna(fname):
        gpx_features.append({})
        continue
    path = find_gpx_path(str(fname), GPX_DIR)
    if path:
        gpx_features.append(extract_gpx_features(path))
    else:
        gpx_features.append({})

df_gpx = pd.DataFrame(gpx_features)

# Pour les colonnes GPX : remplacer NaN par 0 si le fichier GPX existe
mask_avec_gpx = df_gpx['distance_gpx_km'].notna()
cols_gpx = list(df_gpx.columns)
df_gpx.loc[mask_avec_gpx, cols_gpx] = df_gpx.loc[mask_avec_gpx, cols_gpx].fillna(0)

print(f'Features GPX extraites : {df_gpx.shape}')
print(f'Avec GPX : {mask_avec_gpx.sum()}')
print(f'Sans GPX : {(~mask_avec_gpx).sum()}')

  0%|          | 0/7391 [00:00<?, ?it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/2864964498.py:101: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last_5km = float(np.sum(d for d in np.diff(elevations[-last_points:]) if d > 0))
  5%|▍         | 352/7391 [01:40<29:14,  4.01it/s]

  Erreur 2017 Koga Slag om Norg Rest day.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 22%|██▏       | 1618/7391 [06:51<16:22,  5.87it/s]

  Erreur 2018 Tour of Fuzhou Stage 4.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 22%|██▏       | 1625/7391 [06:52<10:58,  8.75it/s]

  Erreur 2018 Africa Cup - TTT.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2018 Africa Cup - ITT.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2018 Africa Cup.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 31%|███       | 2260/7391 [09:30<13:08,  6.51it/s]

  Erreur 2019 Dominican Road National Championships.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 31%|███       | 2274/7391 [09:34<26:10,  3.26it/s]

  Erreur 2019 Georgian Road National Championships.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 33%|███▎      | 2469/7391 [10:21<26:09,  3.14it/s]

  Erreur 2019 Chinese Road National Championships.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 41%|████      | 3032/7391 [12:54<16:18,  4.46it/s]

  Erreur 2020 Chinese Road National Championships.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 45%|████▌     | 3361/7391 [14:34<28:01,  2.40it/s]

  Erreur 2021 Ronde van Limburg.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 51%|█████▏    | 3796/7391 [16:59<23:55,  2.50it/s]

  Erreur 2021 61th Craft Ster van Zwolle.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 54%|█████▍    | 4009/7391 [18:01<23:16,  2.42it/s]

  Erreur 2022 CAC African Road Championships - TTT.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 54%|█████▍    | 4015/7391 [18:03<20:42,  2.72it/s]

  Erreur 2022 CAC African Road Championships - ITT.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 73%|███████▎  | 5432/7391 [25:50<10:56,  2.98it/s]

  Erreur 2023 Grand Prix El Marsa.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 77%|███████▋  | 5674/7391 [26:57<09:43,  2.94it/s]

  Erreur 2024 Tour of Oman Stage 4.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 77%|███████▋  | 5677/7391 [26:58<07:37,  3.75it/s]

  Erreur 2024 Tour of Oman Stage 5.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 84%|████████▍ | 6209/7391 [29:59<06:59,  2.82it/s]

  Erreur 2024 Kreiz Breizh Elites Stage 2.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

 87%|████████▋ | 6424/7391 [31:05<04:59,  3.23it/s]

  Erreur 2024 Tre Valli Varesine.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

100%|██████████| 7391/7391 [34:31<00:00,  3.57it/s]

Features GPX extraites : (7391, 25)
Avec GPX : 7358
Sans GPX : 33

In [7]:
# ── 6. Assemblage final ───────────────────────────────────────────────────────
cols_matching = ['jour', 'mois', 'annee', 'stage', 'nom_pcs', 'categorie', 'fichier_gpx']
cols_komoot_all = ['route_url'] + cols_komoot
cols_gpx_all = list(df_gpx.columns)

df_final = pd.concat([df.reset_index(drop=True), df_gpx.reset_index(drop=True)], axis=1)
cols_finales = [c for c in cols_matching + cols_komoot_all + cols_gpx_all if c in df_final.columns]
df_final = df_final[cols_finales]

print(f'Shape final : {df_final.shape}')
print(f'Colonnes : {list(df_final.columns)}')

Shape final : (7391, 50)
Colonnes : ['jour', 'mois', 'annee', 'stage', 'nom_pcs', 'categorie', 'fichier_gpx', 'route_url', 'road_km', 'street_km', 'state_road_km', 'cycleway_km', 'off-grid_(unknown)_km', 'access_road_km', 'asphalt_km', 'paved_km', 'cobblestones_km', 'unknown_km', 'path_km', 'unpaved_km', 'singletrack_km', 'compacted_gravel_km', 'alpine_km', 'ferry_km', 'alpine_path_km', 'distance_gpx_km', 'denivele_pos', 'denivele_neg', 'altitude_max', 'altitude_min', 'n_cols_cat4', 'n_cols_cat3', 'n_cols_cat2', 'n_cols_cat1', 'n_cols_hc', 'loc_last_col_cat4', 'loc_last_col_cat3', 'loc_last_col_cat2', 'loc_last_col_cat1', 'loc_last_col_hc', 'gradient_last_1km', 'gradient_last_3km', 'gradient_last_5km', 'denivele_last_5km', 'gradient_first_10km', 'gradient_first_20km', 'gradient_first_50km', 'denivele_first_10km', 'denivele_first_20km', 'denivele_first_50km']

In [8]:
# ── 7. Sauvegarde ─────────────────────────────────────────────────────────────
df_final.to_csv(OUTPUT_CSV, index=False)
print(f'Sauvegarde : {OUTPUT_CSV}')
print(f'Shape : {df_final.shape}')

print(f'\nCourses avec Komoot  : {df_final["route_url"].notna().sum()}')
print(f'Courses avec GPX     : {df_final["distance_gpx_km"].notna().sum()}')
print(f'Courses sans Komoot  : {df_final["route_url"].isna().sum()}')
print(f'Courses sans GPX     : {df_final["distance_gpx_km"].isna().sum()}')

print(f'\nNaN restants par colonne :')
nan_cols = df_final.isna().sum()
print(nan_cols[nan_cols > 0].sort_values(ascending=False))

Sauvegarde : /Users/arthurdeletang/Desktop/Stage M1/Code/data/matching/all/dataset_final_v2.csv
Shape : (7391, 50)

Courses avec Komoot  : 7217
Courses avec GPX     : 7358
Courses sans Komoot  : 174
Courses sans GPX     : 33

NaN restants par colonne :
route_url                174
unknown_km               174
road_km                  174
alpine_path_km           174
ferry_km                 174
compacted_gravel_km      174
singletrack_km           174
unpaved_km               174
path_km                  174
alpine_km                174
cobblestones_km          174
asphalt_km               174
access_road_km           174
off-grid_(unknown)_km    174
cycleway_km              174
state_road_km            174
paved_km                 174
street_km                174
denivele_last_5km         33
loc_last_col_hc           33
gradient_last_1km         33
gradient_last_3km         33
gradient_last_5km         33
gradient_first_50km       33
gradient_first_10km       33
gradient_first_20km       33
denivele_first_10km       33
denivele_first_20km       33
loc_last_col_cat2         33
loc_last_col_cat1         33
altitude_max              33
loc_last_col_cat3         33
loc_last_col_cat4         33
n_cols_hc                 33
n_cols_cat1               33
n_cols_cat2               33
n_cols_cat3               33
n_cols_cat4               33
altitude_min              33
denivele_neg              33
denivele_pos              33
distance_gpx_km           33
denivele_first_50km       33
dtype: int64

In [9]:
sans_gpx = df_final[df_final['distance_gpx_km'].isna()][['fichier_gpx', 'annee', 'categorie', 'nom_pcs']]
pd.set_option('display.max_rows', None)
print(sans_gpx.to_string(index=False))

                                                            fichier_gpx  annee categorie                               nom_pcs
                                    2017 Koga Slag om Norg Rest day.gpx   2017       1.1                          slag-om-norg
2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 1.gpx   2018       2.1                 adriatica-ionica-race
2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 2.gpx   2018       2.1                 adriatica-ionica-race
2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 3.gpx   2018       2.1                 adriatica-ionica-race
2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 4.gpx   2018       2.1                 adriatica-ionica-race
2018 Adriatica Ionica Race/Following the Serenissima Routes Stage 5.gpx   2018       2.1                 adriatica-ionica-race
                                        2018 Tour of Fuzhou Stage 4.gpx   2018       2.1                        tour-of-fuzhou
                                              2018 Africa Cup - TTT.gpx   2018       1.2                        africa-cup-ttt
                                              2018 Africa Cup - ITT.gpx   2018       1.2                        africa-cup-itt
                                                    2018 Africa Cup.gpx   2018       1.1                            africa-cup
                         2019 Dominican Road National Championships.gpx   2019        NC                 nc-dominican-republic
                          2019 Georgian Road National Championships.gpx   2019        NC                            nc-georgia
                           2019 Chinese Road National Championships.gpx   2019        NC                              nc-china
                           2020 Chinese Road National Championships.gpx   2020        NC                              nc-china
                                             2021 Ronde van Limburg.gpx   2021       1.1                     ronde-van-limburg
                                    2021 61th Craft Ster van Zwolle.gpx   2021       1.2                       ster-van-zwolle
                          2022 CAC African Road Championships - TTT.gpx   2022        CC     african-cycling-championships-ttt
                          2022 CAC African Road Championships - ITT.gpx   2022        CC african-continental-championships-itt
                    2022 Schaal Sels Merksem/ Johan Museeuw Classic.gpx   2022       1.1                         schaal-schels
                            2023 GP Vorarlberg p/b RadHaus Rankweil.gpx   2023       1.2                         gp-vorarlberg
              2023 Okolo jiznich Cech/Tour of South Bohemia Stage 1.gpx   2023       2.2                    okolo-jiznich-cech
              2023 Okolo jiznich Cech/Tour of South Bohemia Stage 2.gpx   2023       2.2                    okolo-jiznich-cech
              2023 Okolo jiznich Cech/Tour of South Bohemia Stage 3.gpx   2023       2.2                    okolo-jiznich-cech
                                           2023 Grand Prix El Marsa.gpx   2023       1.2                   grand-prix-el-marsa
              2023 Okolo jiznich Cech/Tour of South Bohemia Stage 4.gpx   2023       2.2                    okolo-jiznich-cech
                                  2023 Ixina Gooikse Pijl P/B Lotto.gpx   2023       1.1                          gooikse-pijl
                                          2024 Tour of Oman Stage 4.gpx   2024     2.Pro                          tour-of-oman
                                          2024 Tour of Oman Stage 5.gpx   2024     2.Pro                          tour-of-oman
                           2024 GP Vorarlberg b/by Radhaus Rankweil.gpx   2024       1.2                         gp-vorarlberg
                                   2024 Kreiz Breizh Elites Stage 2.gpx   2024       2.2                   kreiz-breizh-elites
                                2024 Alfasun Gooikse Pijl p/b Lotto.gpx   2024       1.1                          gooikse-pijl
                                            2024 Tre Valli Varesine.gpx   2024     1.Pro                    tre-valli-varesine
                            2025 GP Vorarlberg p/b Radhaus Rankweil.gpx   2025       1.2                         gp-vorarlberg

In [11]:
import pandas as pd

RACE_PATH = '/Users/arthurdeletang/Desktop/Stage M1/Code/race_data/race_features.csv'

df_race = pd.read_csv(RACE_PATH)

cols_gpx = ['distance_gpx_km', 'denivele_pos', 'altitude_max', 'n_cols_hc', 'gradient_last_1km']
cols_gpx = [c for c in cols_gpx if c in df_race.columns]

mask_zeros = (df_race[cols_gpx] == 0).all(axis=1)
print(f'Courses avec GPX = 0 partout : {mask_zeros.sum()}')
df_race[mask_zeros][['course', 'year', 'stage_num'] + cols_gpx].sort_values(['course', 'year'])

Courses avec GPX = 0 partout : 161

,course,year,stage_num,distance_gpx_km,denivele_pos,altitude_max,n_cols_hc,gradient_last_1km
220,4-jours-de-dunkerque,2017,1.0,0.0,0.0,0.0,0.0,0.0
223,4-jours-de-dunkerque,2017,2.0,0.0,0.0,0.0,0.0,0.0
225,4-jours-de-dunkerque,2017,3.0,0.0,0.0,0.0,0.0,0.0
227,4-jours-de-dunkerque,2017,4.0,0.0,0.0,0.0,0.0,0.0
230,4-jours-de-dunkerque,2017,5.0,0.0,0.0,0.0,0.0,0.0
234,4-jours-de-dunkerque,2017,6.0,0.0,0.0,0.0,0.0,0.0
987,4-jours-de-dunkerque,2018,1.0,0.0,0.0,0.0,0.0,0.0
990,4-jours-de-dunkerque,2018,2.0,0.0,0.0,0.0,0.0,0.0
991,4-jours-de-dunkerque,2018,3.0,0.0,0.0,0.0,0.0,0.0
995,4-jours-de-dunkerque,2018,4.0,0.0,0.0,0.0,0.0,0.0
1002,4-jours-de-dunkerque,2018,5.0,0.0,0.0,0.0,0.0,0.0
1004,4-jours-de-dunkerque,2018,6.0,0.0,0.0,0.0,0.0,0.0
2028,4-jours-de-dunkerque,2019,1.0,0.0,0.0,0.0,0.0,0.0
2033,4-jours-de-dunkerque,2019,2.0,0.0,0.0,0.0,0.0,0.0
2034,4-jours-de-dunkerque,2019,3.0,0.0,0.0,0.0,0.0,0.0
2041,4-jours-de-dunkerque,2019,4.0,0.0,0.0,0.0,0.0,0.0
2050,4-jours-de-dunkerque,2019,5.0,0.0,0.0,0.0,0.0,0.0
2052,4-jours-de-dunkerque,2019,6.0,0.0,0.0,0.0,0.0,0.0
4125,4-jours-de-dunkerque,2022,1.0,0.0,0.0,0.0,0.0,0.0
4128,4-jours-de-dunkerque,2022,2.0,0.0,0.0,0.0,0.0,0.0
4129,4-jours-de-dunkerque,2022,3.0,0.0,0.0,0.0,0.0,0.0
4133,4-jours-de-dunkerque,2022,4.0,0.0,0.0,0.0,0.0,0.0
4136,4-jours-de-dunkerque,2022,5.0,0.0,0.0,0.0,0.0,0.0
4141,4-jours-de-dunkerque,2022,6.0,0.0,0.0,0.0,0.0,0.0
5013,4-jours-de-dunkerque,2023,1.0,0.0,0.0,0.0,0.0,0.0
5015,4-jours-de-dunkerque,2023,2.0,0.0,0.0,0.0,0.0,0.0
5020,4-jours-de-dunkerque,2023,3.0,0.0,0.0,0.0,0.0,0.0
5022,4-jours-de-dunkerque,2023,4.0,0.0,0.0,0.0,0.0,0.0
5029,4-jours-de-dunkerque,2023,5.0,0.0,0.0,0.0,0.0,0.0
5038,4-jours-de-dunkerque,2023,6.0,0.0,0.0,0.0,0.0,0.0
5942,4-jours-de-dunkerque,2024,1.0,0.0,0.0,0.0,0.0,0.0
5945,4-jours-de-dunkerque,2024,2.0,0.0,0.0,0.0,0.0,0.0
5948,4-jours-de-dunkerque,2024,3.0,0.0,0.0,0.0,0.0,0.0
5951,4-jours-de-dunkerque,2024,4.0,0.0,0.0,0.0,0.0,0.0
5955,4-jours-de-dunkerque,2024,5.0,0.0,0.0,0.0,0.0,0.0
5962,4-jours-de-dunkerque,2024,6.0,0.0,0.0,0.0,0.0,0.0
6838,4-jours-de-dunkerque,2025,1.0,0.0,0.0,0.0,0.0,0.0
6841,4-jours-de-dunkerque,2025,2.0,0.0,0.0,0.0,0.0,0.0
6844,4-jours-de-dunkerque,2025,3.0,0.0,0.0,0.0,0.0,0.0
6846,4-jours-de-dunkerque,2025,4.0,0.0,0.0,0.0,0.0,0.0
6850,4-jours-de-dunkerque,2025,5.0,0.0,0.0,0.0,0.0,0.0
1166,adriatica-ionica-race,2018,1.0,0.0,0.0,0.0,0.0,0.0
1167,adriatica-ionica-race,2018,2.0,0.0,0.0,0.0,0.0,0.0
1172,adriatica-ionica-race,2018,3.0,0.0,0.0,0.0,0.0,0.0
1175,adriatica-ionica-race,2018,4.0,0.0,0.0,0.0,0.0,0.0
1179,adriatica-ionica-race,2018,5.0,0.0,0.0,0.0,0.0,0.0
2347,adriatica-ionica-race,2019,1.0,0.0,0.0,0.0,0.0,0.0
2357,adriatica-ionica-race,2019,2.0,0.0,0.0,0.0,0.0,0.0
2362,adriatica-ionica-race,2019,3.0,0.0,0.0,0.0,0.0,0.0
2367,adriatica-ionica-race,2019,4.0,0.0,0.0,0.0,0.0,0.0
3441,adriatica-ionica-race,2021,1.0,0.0,0.0,0.0,0.0,0.0
3442,adriatica-ionica-race,2021,2.0,0.0,0.0,0.0,0.0,0.0
3443,adriatica-ionica-race,2021,3.0,0.0,0.0,0.0,0.0,0.0
4230,adriatica-ionica-race,2022,1.0,0.0,0.0,0.0,0.0,0.0
4241,adriatica-ionica-race,2022,2.0,0.0,0.0,0.0,0.0,0.0
4244,adriatica-ionica-race,2022,3.0,0.0,0.0,0.0,0.0,0.0
4247,adriatica-ionica-race,2022,4.0,0.0,0.0,0.0,0.0,0.0
4250,adriatica-ionica-race,2022,5.0,0.0,0.0,0.0,0.0,0.0
1623,africa-cup,2018,NaN,0.0,0.0,0.0,0.0,0.0
1622,africa-cup-itt,2018,NaN,0.0,0.0,0.0,0.0,0.0
1621,africa-cup-ttt,2018,NaN,0.0,0.0,0.0,0.0,0.0
4015,african-continental-championships-itt,2022,NaN,0.0,0.0,0.0,0.0,0.0
4009,african-cycling-championships-ttt,2022,NaN,0.0,0.0,0.0,0.0,0.0
3013,antwerp-port-epic,2020,NaN,0.0,0.0,0.0,0.0,0.0
3719,antwerp-port-epic,2021,NaN,0.0,0.0,0.0,0.0,0.0
4174,antwerp-port-epic,2022,NaN,0.0,0.0,0.0,0.0,0.0
5035,antwerp-port-epic,2023,NaN,0.0,0.0,0.0,0.0,0.0
5960,antwerp-port-epic,2024,NaN,0.0,0.0,0.0,0.0,0.0
6938,antwerp-port-epic,2025,NaN,0.0,0.0,0.0,0.0,0.0
6836,classique-dunkerque,2025,NaN,0.0,0.0,0.0,0.0,0.0
134,dwars-door-vlaanderen,2017,NaN,0.0,0.0,0.0,0.0,0.0
812,dwars-door-vlaanderen,2018,NaN,0.0,0.0,0.0,0.0,0.0
4036,dwars-door-vlaanderen,2022,NaN,0.0,0.0,0.0,0.0,0.0
5465,gooikse-pijl,2023,NaN,0.0,0.0,0.0,0.0,0.0
6379,gooikse-pijl,2024,NaN,0.0,0.0,0.0,0.0,0.0
176,gp-de-denain,2017,NaN,0.0,0.0,0.0,0.0,0.0
502,gp-de-fourmies,2017,NaN,0.0,0.0,0.0,0.0,0.0
1421,gp-de-fourmies,2018,NaN,0.0,0.0,0.0,0.0,0.0
2523,gp-de-fourmies,2019,NaN,0.0,0.0,0.0,0.0,0.0
3720,gp-de-fourmies,2021,NaN,0.0,0.0,0.0,0.0,0.0
4554,gp-de-fourmies,2022,NaN,0.0,0.0,0.0,0.0,0.0
5433,gp-de-fourmies,2023,NaN,0.0,0.0,0.0,0.0,0.0
6345,gp-de-fourmies,2024,NaN,0.0,0.0,0.0,0.0,0.0
7261,gp-de-fourmies,2025,NaN,0.0,0.0,0.0,0.0,0.0
260,gp-de-la-somme,2017,NaN,0.0,0.0,0.0,0.0,0.0
2023,gp-de-la-somme,2019,NaN,0.0,0.0,0.0,0.0,0.0
4965,gp-vorarlberg,2023,NaN,0.0,0.0,0.0,0.0,0.0
5891,gp-vorarlberg,2024,NaN,0.0,0.0,0.0,0.0,0.0
6799,gp-vorarlberg,2025,NaN,0.0,0.0,0.0,0.0,0.0
5432,grand-prix-el-marsa,2023,NaN,0.0,0.0,0.0,0.0,0.0
6209,kreiz-breizh-elites,2024,2.0,0.0,0.0,0.0,0.0,0.0
3775,memorial-frank-vandenbroucke,2021,NaN,0.0,0.0,0.0,0.0,0.0
5516,memorial-frank-vandenbroucke,2023,NaN,0.0,0.0,0.0,0.0,0.0
6396,memorial-frank-vandenbroucke,2024,NaN,0.0,0.0,0.0,0.0,0.0
7323,memorial-frank-vandenbroucke,2025,NaN,0.0,0.0,0.0,0.0,0.0
4611,memorial-rik-van-steenbergen,2022,NaN,0.0,0.0,0.0,0.0,0.0
2469,nc-china,2019,NaN,0.0,0.0,0.0,0.0,0.0
3030,nc-china,2020,NaN,0.0,0.0,0.0,0.0,0.0
2258,nc-dominican-republic,2019,NaN,0.0,0.0,0.0,0.0,0.0
2274,nc-georgia,2019,NaN,0.0,0.0,0.0,0.0,0.0
2893,nc-ukraine-itt,2020,NaN,0.0,0.0,0.0,0.0,0.0
1429,okolo-jiznich-cech,2018,1.0,0.0,0.0,0.0,0.0,0.0
1433,okolo-jiznich-cech,2018,2.0,0.0,0.0,0.0,0.0,0.0
1438,okolo-jiznich-cech,2018,3.0,0.0,0.0,0.0,0.0,0.0
1444,okolo-jiznich-cech,2018,4.0,0.0,0.0,0.0,0.0,0.0
1450,okolo-jiznich-cech,2018,5.0,0.0,0.0,0.0,0.0,0.0
3706,okolo-jiznich-cech,2021,1.0,0.0,0.0,0.0,0.0,0.0
3710,okolo-jiznich-cech,2021,2.0,0.0,0.0,0.0,0.0,0.0
3715,okolo-jiznich-cech,2021,3.0,0.0,0.0,0.0,0.0,0.0
3717,okolo-jiznich-cech,2021,4.0,0.0,0.0,0.0,0.0,0.0
4539,okolo-jiznich-cech,2022,1.0,0.0,0.0,0.0,0.0,0.0
4542,okolo-jiznich-cech,2022,2.0,0.0,0.0,0.0,0.0,0.0
4546,okolo-jiznich-cech,2022,3.0,0.0,0.0,0.0,0.0,0.0
4552,okolo-jiznich-cech,2022,4.0,0.0,0.0,0.0,0.0,0.0
5413,okolo-jiznich-cech,2023,1.0,0.0,0.0,0.0,0.0,0.0
5419,okolo-jiznich-cech,2023,2.0,0.0,0.0,0.0,0.0,0.0
5425,okolo-jiznich-cech,2023,3.0,0.0,0.0,0.0,0.0,0.0
5436,okolo-jiznich-cech,2023,4.0,0.0,0.0,0.0,0.0,0.0
6327,okolo-jiznich-cech,2024,1.0,0.0,0.0,0.0,0.0,0.0
6332,okolo-jiznich-cech,2024,2.0,0.0,0.0,0.0,0.0,0.0
6340,okolo-jiznich-cech,2024,3.0,0.0,0.0,0.0,0.0,0.0
6350,okolo-jiznich-cech,2024,4.0,0.0,0.0,0.0,0.0,0.0
7201,okolo-jiznich-cech,2025,1.0,0.0,0.0,0.0,0.0,0.0
7208,okolo-jiznich-cech,2025,2.0,0.0,0.0,0.0,0.0,0.0
7215,okolo-jiznich-cech,2025,3.0,0.0,0.0,0.0,0.0,0.0
7225,okolo-jiznich-cech,2025,4.0,0.0,0.0,0.0,0.0,0.0
3727,okolo-slovenska,2021,NaN,0.0,0.0,0.0,0.0,0.0
3729,okolo-slovenska,2021,1.0,0.0,0.0,0.0,0.0,0.0
3733,okolo-slovenska,2021,2.0,0.0,0.0,0.0,0.0,0.0
3736,okolo-slovenska,2021,3.0,0.0,0.0,0.0,0.0,0.0
3743,okolo-slovenska,2021,4.0,0.0,0.0,0.0,0.0,0.0
5449,okolo-slovenska,2023,1.0,0.0,0.0,0.0,0.0,0.0
5453,okolo-slovenska,2023,2.0,0.0,0.0,0.0,0.0,0.0
5458,okolo-slovenska,2023,3.0,0.0,0.0,0.0,0.0,0.0
5459,okolo-slovenska,2023,4.0,0.0,0.0,0.0,0.0,0.0
5467,okolo-slovenska,2023,5.0,0.0,0.0,0.0,0.0,0.0
6121,okolo-slovenska,2024,1.0,0.0,0.0,0.0,0.0,0.0
6123,okolo-slovenska,2024,3.0,0.0,0.0,0.0,0.0,0.0
6125,okolo-slovenska,2024,4.0,0.0,0.0,0.0,0.0,0.0
6127,okolo-slovenska,2024,5.0,0.0,0.0,0.0,0.0,0.0
7268,okolo-slovenska,2025,1.0,0.0,0.0,0.0,0.0,0.0
7271,okolo-slovenska,2025,2.0,0.0,0.0,0.0,0.0,0.0
7273,okolo-slovenska,2025,3.0,0.0,0.0,0.0,0.0,0.0
7278,okolo-slovenska,2025,4.0,0.0,0.0,0.0,0.0,0.0
7287,okolo-slovenska,2025,5.0,0.0,0.0,0.0,0.0,0.0
1026,paris-arras-tour,2018,1.0,0.0,0.0,0.0,0.0,0.0
1032,paris-arras-tour,2018,2.0,0.0,0.0,0.0,0.0,0.0
1044,paris-arras-tour,2018,3.0,0.0,0.0,0.0,0.0,0.0
2074,paris-arras-tour,2019,1.0,0.0,0.0,0.0,0.0,0.0
2082,paris-arras-tour,2019,2.0,0.0,0.0,0.0,0.0,0.0
2088,paris-arras-tour,2019,3.0,0.0,0.0,0.0,0.0,0.0
3361,ronde-van-limburg,2021,NaN,0.0,0.0,0.0,0.0,0.0
4485,schaal-schels,2022,NaN,0.0,0.0,0.0,0.0,0.0
353,slag-om-norg,2017,NaN,0.0,0.0,0.0,0.0,0.0
3796,ster-van-zwolle,2021,NaN,0.0,0.0,0.0,0.0,0.0
1220,tour-de-delta,2018,NaN,0.0,0.0,0.0,0.0,0.0
2292,tour-de-delta,2019,NaN,0.0,0.0,0.0,0.0,0.0
1616,tour-of-fuzhou,2018,4.0,0.0,0.0,0.0,0.0,0.0
5675,tour-of-oman,2024,4.0,0.0,0.0,0.0,0.0,0.0
5677,tour-of-oman,2024,5.0,0.0,0.0,0.0,0.0,0.0
6424,tre-valli-varesine,2024,NaN,0.0,0.0,0.0,0.0,0.0

In [12]:
import os, re
import numpy as np
import pandas as pd
import gpxpy
from scipy.signal import find_peaks
from tqdm import tqdm

GPX_DIR  = '/Users/arthurdeletang/Desktop/Stage M1/Code/data/gpx_files_2'
RACE_PATH = '/Users/arthurdeletang/Desktop/Stage M1/Code/race_data/race_features.csv'

df_race = pd.read_csv(RACE_PATH)

# Identifier les lignes avec GPX = 0 partout
cols_gpx_check = ['distance_gpx_km', 'denivele_pos', 'altitude_max']
cols_gpx_check = [c for c in cols_gpx_check if c in df_race.columns]
mask_zeros = (df_race[cols_gpx_check] == 0).all(axis=1)
print(f'Lignes avec GPX = 0 : {mask_zeros.sum()}')

# Voir quels fichier_gpx correspondent
# On reconstruit depuis nom_pcs + year + stage_num
# Chercher dans GPX_DIR les fichiers correspondants
def find_gpx_path(fname, gpx_dir):
    if pd.isna(fname):
        return None
    full = os.path.join(gpx_dir, fname)
    if os.path.exists(full):
        return full
    replaced = fname.replace(' / ', ' - ').replace('/', ' - ')
    if os.path.exists(os.path.join(gpx_dir, replaced)):
        return os.path.join(gpx_dir, replaced)
    base = fname.split(' / ')[0].split('/')[0].strip()
    for candidate in [base + ' .gpx', base + '.gpx']:
        if os.path.exists(os.path.join(gpx_dir, candidate)):
            return os.path.join(gpx_dir, candidate)
    return None

# Verifier que le fichier gpx existe pour les lignes à 0
if 'fichier_gpx' in df_race.columns:
    df_zeros = df_race[mask_zeros][['fichier_gpx']].copy()
    df_zeros['path'] = df_zeros['fichier_gpx'].apply(lambda x: find_gpx_path(str(x), GPX_DIR))
    print(f'Fichiers trouves : {df_zeros["path"].notna().sum()}/{len(df_zeros)}')
    print(df_zeros[df_zeros['path'].notna()].head(5))

Lignes avec GPX = 0 : 161

In [15]:
def parse_gpx_safe(filepath):
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
    content = re.sub(r'&(?!amp;|lt;|gt;|quot;|apos;|#)', '&amp;', content)
    return gpxpy.parse(content)

def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    dlat, dlon = np.radians(lat2-lat1), np.radians(lon2-lon1)
    a = np.sin(dlat/2)**2 + np.cos(np.radians(lat1)) * np.cos(np.radians(lat2)) * np.sin(dlon/2)**2
    return R * 2 * np.arcsin(np.sqrt(a))

def get_number_peaks(series, prominence):
    store = find_peaks(series, prominence=prominence)
    try:
        if (len(store[0]) > 1) and (np.min(np.diff(store[0])) < prominence):
            return len(store[1]['prominences'][np.diff(np.insert(store[0], 0, 0)) > prominence])
        return len(store[1]['prominences'])
    except:
        return len(store[1]['prominences'])

def gradient_last_km(lats, lons, elevations, km):
    dist_cumul = 0.0
    for i in range(len(lats)-1, 0, -1):
        dist_cumul += haversine(lats[i-1], lons[i-1], lats[i], lons[i])
        if dist_cumul >= km:
            return round((elevations[-1] - elevations[i-1]) / (km * 1000) * 100, 2)
    total = sum(haversine(lats[i], lons[i], lats[i+1], lons[i+1]) for i in range(len(lats)-1))
    return round((elevations[-1] - elevations[0]) / (total * 1000) * 100, 2) if total > 0 else 0.0

def gradient_first_km(lats, lons, elevations, km):
    dist_cumul = 0.0
    for i in range(len(lats)-1):
        dist_cumul += haversine(lats[i], lons[i], lats[i+1], lons[i+1])
        if dist_cumul >= km:
            return round((elevations[i+1] - elevations[0]) / (km * 1000) * 100, 2)
    total = sum(haversine(lats[i], lons[i], lats[i+1], lons[i+1]) for i in range(len(lats)-1))
    return round((elevations[-1] - elevations[0]) / (total * 1000) * 100, 2) if total > 0 else 0.0

def denivele_first_km(lats, lons, elevations, km):
    dist_cumul, deniv = 0.0, 0.0
    for i in range(len(lats)-1):
        dist_cumul += haversine(lats[i], lons[i], lats[i+1], lons[i+1])
        diff = elevations[i+1] - elevations[i]
        if diff > 0:
            deniv += diff
        if dist_cumul >= km:
            break
    return round(deniv, 0)

def extract_gpx_features(filepath):
    try:
        gpx = parse_gpx_safe(filepath)
        points = gpx.tracks[0].segments[0].points
        elevations = [p.elevation or 0 for p in points]
        lats = [p.latitude for p in points]
        lons = [p.longitude for p in points]
        if len(lats) < 2:
            return None

        dist = sum(haversine(lats[i], lons[i], lats[i+1], lons[i+1]) for i in range(len(lats)-1))
        elev_diff = np.diff(elevations)
        elev_series = elevations + [0]
        n = len(elev_series)

        def loc_last(p):
            peaks = find_peaks(elev_series, prominence=p)[0]
            return float(np.max(peaks) / n) if len(peaks) > 0 else 0.0

        last_pts = min(500, len(elevations))
        deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))

        return {
            'distance_gpx_km':   round(dist, 2),
            'denivele_pos':      round(float(np.sum(elev_diff[elev_diff > 0])), 0),
            'denivele_neg':      round(float(np.abs(np.sum(elev_diff[elev_diff < 0]))), 0),
            'altitude_max':      round(float(np.max(elevations)), 0),
            'altitude_min':      round(float(np.min(elevations)), 0),
            'n_cols_hc':  get_number_peaks(elev_series, 800),
            'n_cols_cat1': get_number_peaks(elev_series, 640) - get_number_peaks(elev_series, 800),
            'n_cols_cat2': get_number_peaks(elev_series, 320) - get_number_peaks(elev_series, 640),
            'n_cols_cat3': get_number_peaks(elev_series, 160) - get_number_peaks(elev_series, 320),
            'n_cols_cat4': get_number_peaks(elev_series, 80)  - get_number_peaks(elev_series, 160),
            'loc_last_col_cat4': round(loc_last(80), 4),
            'loc_last_col_cat3': round(loc_last(160), 4),
            'loc_last_col_cat2': round(loc_last(320), 4),
            'loc_last_col_cat1': round(loc_last(640), 4),
            'loc_last_col_hc':   round(loc_last(800), 4),
            'gradient_last_1km': gradient_last_km(lats, lons, elevations, 1),
            'gradient_last_3km': gradient_last_km(lats, lons, elevations, 3),
            'gradient_last_5km': gradient_last_km(lats, lons, elevations, 5),
            'denivele_last_5km': round(deniv_last, 0),
            'gradient_first_50km': gradient_first_km(lats, lons, elevations, 50),
            'denivele_first_50km': denivele_first_km(lats, lons, elevations, 50),
        }
    except Exception as e:
        print(f'  Erreur {os.path.basename(filepath)} : {e}')
        return None

# Corriger les lignes à 0
n_updated = 0
for idx in tqdm(df_race[mask_zeros].index):
    fname = df_race.loc[idx, 'fichier_gpx'] if 'fichier_gpx' in df_race.columns else None
    if pd.isna(fname):
        continue
    path = find_gpx_path(str(fname), GPX_DIR)
    if path is None:
        continue
    feats = extract_gpx_features(path)
    if feats is None:
        continue
    for col, val in feats.items():
        if col in df_race.columns:
            df_race.loc[idx, col] = val
    n_updated += 1

print(f'\nLignes mises a jour : {n_updated}')

# Verifier
mask_zeros_after = (df_race[cols_gpx_check] == 0).all(axis=1)
print(f'Lignes encore a 0 : {mask_zeros_after.sum()}')

# Sauvegarder
df_race.to_csv(RACE_PATH, index=False)
print(f'race_features.csv mis a jour')

100%|██████████| 161/161 [00:00<00:00, 549010.52it/s]

Lignes mises a jour : 0
Lignes encore a 0 : 161
race_features.csv mis a jour

In [16]:
print(df_race.columns.tolist())
print(df_race.head(2))

['date', 'year', 'course', 'stage', 'stage_num', 'classification', 'distance_gpx_km', 'asphalt_km', 'paved_km', 'cobblestones_km', 'unpaved_km', 'compacted_gravel_km', 'road_km', 'street_km', 'state_road_km', 'cycleway_km', 'off-grid_(unknown)_km', 'access_road_km', 'unknown_km', 'path_km', 'singletrack_km', 'denivele_pos', 'denivele_neg', 'altitude_max', 'altitude_min', 'n_cols_cat4', 'n_cols_cat3', 'n_cols_cat2', 'n_cols_cat1', 'n_cols_hc', 'loc_last_col_cat4', 'loc_last_col_cat3', 'loc_last_col_cat2', 'loc_last_col_cat1', 'loc_last_col_hc', 'gradient_last_1km', 'gradient_last_3km', 'gradient_last_5km', 'denivele_last_5km', 'gradient_first_50km', 'denivele_first_50km']
         date  year              course   stage  stage_num classification  \
0  2017-01-05  2017    nc-australia-itt  result        NaN             NC
1  2017-01-06  2017  nc-new-zealand-itt  result        NaN             NC

   distance_gpx_km  asphalt_km  paved_km  cobblestones_km  ...  \
0            40.79         0.0      40.8              0.0  ...
1            40.40        16.3      23.8              0.0  ...

   loc_last_col_cat3  loc_last_col_cat2  loc_last_col_cat1  loc_last_col_hc  \
0                0.0                0.0                0.0              0.0
1                0.0                0.0                0.0              0.0

   gradient_last_1km  gradient_last_3km  gradient_last_5km  denivele_last_5km  \
0                2.0               1.47               1.24              306.0
1                0.5              -1.63              -0.22              178.0

   gradient_first_50km  denivele_first_50km
0                -0.01                423.0
1                -0.01                342.0

[2 rows x 41 columns]

In [22]:
import os, re
import numpy as np
import pandas as pd
import gpxpy
from scipy.signal import find_peaks
from tqdm import tqdm

GPX_DIR = '/Users/arthurdeletang/Desktop/Stage M1/Code/data/gpx_files_2'
MATCH_DIR = '/Users/arthurdeletang/Desktop/Stage M1/Code/data/matching/all'

# Charger tous les matchings pour avoir course -> fichier_gpx
dfs_match = []
for year in range(2017, 2026):
    path = os.path.join(MATCH_DIR, f'matching_{year}.csv')
    if os.path.exists(path):
        df = pd.read_csv(path)
        df = df[df['statut'] == 'match']
        dfs_match.append(df[['nom_pcs', 'annee', 'stage', 'fichier_gpx']])

df_match_all = pd.concat(dfs_match, ignore_index=True)

# Creer un mapping course+year+stage -> fichier_gpx
def stage_to_num(s):
    if pd.isna(s) or s == 'result':
        return np.nan
    if 'stage_' in str(s):
        try:
            return float(str(s).replace('stage_', ''))
        except:
            return np.nan
    if s == 'prologue':
        return 0.0
    return np.nan

df_match_all['stage_num'] = df_match_all['stage'].apply(stage_to_num)

# Joindre avec race_features pour recuperer fichier_gpx
df_race_with_gpx = df_race.merge(
    df_match_all[['nom_pcs', 'annee', 'stage_num', 'fichier_gpx']].rename(
        columns={'nom_pcs': 'course', 'annee': 'year'}),
    on=['course', 'year', 'stage_num'],
    how='left'
)

# Dedupliquer en gardant la premiere correspondance
df_race_with_gpx = df_race_with_gpx.drop_duplicates(subset=['course', 'year', 'stage_num'])
print(f'Shape apres dedup : {df_race_with_gpx.shape}')

cols_check = ['distance_gpx_km', 'denivele_pos', 'altitude_max']
mask_zeros = (df_race_with_gpx[cols_check] == 0).all(axis=1)
print(f'Lignes a corriger : {mask_zeros.sum()}')

df_zeros = df_race_with_gpx[mask_zeros]
print(f'Avec fichier_gpx : {df_zeros["fichier_gpx"].notna().sum()}')
print(df_zeros[['course', 'year', 'stage_num', 'fichier_gpx']].head(10))

Shape apres dedup : (7391, 42)
Lignes a corriger : 161
Avec fichier_gpx : 160
                    course  year  stage_num  \
134  dwars-door-vlaanderen  2017        NaN
176           gp-de-denain  2017        NaN
220   4-jours-de-dunkerque  2017        1.0
223   4-jours-de-dunkerque  2017        2.0
225   4-jours-de-dunkerque  2017        3.0
227   4-jours-de-dunkerque  2017        4.0
230   4-jours-de-dunkerque  2017        5.0
234   4-jours-de-dunkerque  2017        6.0
260         gp-de-la-somme  2017        NaN
353           slag-om-norg  2017        NaN

                                           fichier_gpx
134  2017 Dwars Door Vlaanderen - A travers la Flan...
176  2017 GP de Denain - Porte du Hainaut - Valenci...
220  2017 4 Jours de Dunkerque - Grand Prix des Hau...
223  2017 4 Jours de Dunkerque - Grand Prix des Hau...
225  2017 4 Jours de Dunkerque - Grand Prix des Hau...
227  2017 4 Jours de Dunkerque - Grand Prix des Hau...
230  2017 4 Jours de Dunkerque - Grand Prix des Hau...
234  2017 4 Jours de Dunkerque - Grand Prix des Hau...
260  2017 Grand Prix de la Somme - Conseil Departem...
353                2017 Koga Slag om Norg Rest day.gpx

In [ ]:
n_updated = 0

for idx in tqdm(df_race_with_gpx[mask_zeros].index):
    fname = df_race_with_gpx.loc[idx, 'fichier_gpx']
    if pd.isna(fname):
        continue

    path = find_gpx_path(str(fname), GPX_DIR)
    if path is None:
        continue

    feats = extract_gpx_features(path)
    if feats is None:
        continue

    for col, val in feats.items():
        if col in df_race_with_gpx.columns:
            df_race_with_gpx.loc[idx, col] = val
    n_updated += 1

print(f'Lignes mises a jour : {n_updated}')

# Verifier
mask_zeros_after = (df_race_with_gpx[cols_check] == 0).all(axis=1)
print(f'Lignes encore a 0 : {mask_zeros_after.sum()}')

# Sauvegarder sans la colonne fichier_gpx
df_race_with_gpx.drop(columns=['fichier_gpx']).to_csv(RACE_PATH, index=False)
print('race_features.csv mis a jour')

  0%|          | 0/161 [00:00<?, ?it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  1%|          | 1/161 [00:00<01:15,  2.11it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  1%|          | 2/161 [00:00<01:05,  2.43it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  2%|▏         | 3/161 [00:01<00:59,  2.64it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  2%|▏         | 4/161 [00:01<00:55,  2.84it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  3%|▎         | 5/161 [00:01<00:48,  3.24it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  4%|▎         | 6/161 [00:02<00:49,  3.11it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  4%|▍         | 7/161 [00:02<01:03,  2.42it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  5%|▍         | 8/161 [00:02<00:58,  2.62it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  7%|▋         | 11/161 [00:03<00:31,  4.73it/s]

  Erreur 2017 Koga Slag om Norg Rest day.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  7%|▋         | 12/161 [00:03<00:32,  4.56it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  8%|▊         | 13/161 [00:03<00:37,  3.96it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  9%|▊         | 14/161 [00:04<00:40,  3.59it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
  9%|▉         | 15/161 [00:04<00:44,  3.27it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 10%|▉         | 16/161 [00:04<00:46,  3.12it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 11%|█         | 17/161 [00:05<00:52,  2.75it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 11%|█         | 18/161 [00:05<00:50,  2.86it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 12%|█▏        | 19/161 [00:05<00:44,  3.18it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 12%|█▏        | 20/161 [00:06<00:49,  2.87it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 13%|█▎        | 21/161 [00:06<00:49,  2.86it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 15%|█▍        | 24/161 [00:06<00:24,  5.59it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 17%|█▋        | 27/161 [00:07<00:17,  7.88it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 18%|█▊        | 29/161 [00:07<00:20,  6.47it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 19%|█▊        | 30/161 [00:07<00:21,  6.09it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 20%|█▉        | 32/161 [00:07<00:20,  6.44it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 20%|██        | 33/161 [00:08<00:21,  5.93it/s]

  Erreur 2018 Tour of Fuzhou Stage 4.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2018 Africa Cup - TTT.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2018 Africa Cup - ITT.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2018 Africa Cup.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 24%|██▎       | 38/161 [00:08<00:15,  8.06it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 24%|██▍       | 39/161 [00:09<00:19,  6.27it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 25%|██▍       | 40/161 [00:09<00:22,  5.30it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 25%|██▌       | 41/161 [00:09<00:26,  4.53it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 26%|██▌       | 42/161 [00:10<00:30,  3.87it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 27%|██▋       | 43/161 [00:10<00:34,  3.38it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 27%|██▋       | 44/161 [00:10<00:36,  3.21it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 28%|██▊       | 45/161 [00:11<00:33,  3.49it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 29%|██▊       | 46/161 [00:11<00:36,  3.12it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 29%|██▉       | 47/161 [00:11<00:40,  2.78it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 31%|███       | 50/161 [00:12<00:20,  5.51it/s]

  Erreur 2019 Dominican Road National Championships.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2019 Georgian Road National Championships.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 32%|███▏      | 52/161 [00:12<00:26,  4.08it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 33%|███▎      | 53/161 [00:13<00:31,  3.38it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 34%|███▎      | 54/161 [00:13<00:29,  3.60it/s]

  Erreur 2019 Chinese Road National Championships.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 35%|███▍      | 56/161 [00:13<00:22,  4.63it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 35%|███▌      | 57/161 [00:14<00:26,  3.94it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 36%|███▌      | 58/161 [00:14<00:25,  4.08it/s]

  Erreur 2020 Chinese Road National Championships.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2021 Ronde van Limburg.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 38%|███▊      | 61/161 [00:14<00:18,  5.55it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 39%|███▊      | 62/161 [00:15<00:21,  4.62it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 39%|███▉      | 63/161 [00:15<00:20,  4.79it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 40%|████      | 65/161 [00:15<00:17,  5.46it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 41%|████      | 66/161 [00:15<00:20,  4.67it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 42%|████▏     | 67/161 [00:16<00:22,  4.15it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 42%|████▏     | 68/161 [00:16<00:23,  3.96it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 43%|████▎     | 69/161 [00:16<00:27,  3.39it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 44%|████▍     | 71/161 [00:17<00:21,  4.15it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 45%|████▍     | 72/161 [00:17<00:21,  4.06it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 45%|████▌     | 73/161 [00:17<00:24,  3.66it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 46%|████▌     | 74/161 [00:18<00:23,  3.77it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 47%|████▋     | 75/161 [00:18<00:23,  3.65it/s]

  Erreur 2021 61th Craft Ster van Zwolle.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2022 CAC African Road Championships - TTT.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2022 CAC African Road Championships - ITT.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 49%|████▉     | 79/161 [00:18<00:12,  6.65it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 50%|████▉     | 80/161 [00:19<00:14,  5.58it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 50%|█████     | 81/161 [00:19<00:18,  4.36it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 51%|█████     | 82/161 [00:19<00:20,  3.86it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 52%|█████▏    | 83/161 [00:20<00:22,  3.45it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 52%|█████▏    | 84/161 [00:20<00:27,  2.79it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 53%|█████▎    | 85/161 [00:21<00:27,  2.81it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 53%|█████▎    | 86/161 [00:21<00:23,  3.15it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 54%|█████▍    | 87/161 [00:21<00:24,  2.99it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 55%|█████▍    | 88/161 [00:22<00:25,  2.89it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 55%|█████▌    | 89/161 [00:22<00:24,  2.98it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 56%|█████▌    | 90/161 [00:22<00:25,  2.84it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 57%|█████▋    | 91/161 [00:23<00:25,  2.77it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 58%|█████▊    | 94/161 [00:23<00:15,  4.42it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 59%|█████▉    | 95/161 [00:23<00:15,  4.27it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 60%|█████▉    | 96/161 [00:24<00:15,  4.24it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 60%|██████    | 97/161 [00:24<00:17,  3.59it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 61%|██████    | 98/161 [00:24<00:16,  3.88it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 61%|██████▏   | 99/161 [00:25<00:18,  3.34it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 62%|██████▏   | 100/161 [00:25<00:21,  2.90it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 63%|██████▎   | 101/161 [00:25<00:21,  2.75it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 64%|██████▍   | 103/161 [00:26<00:18,  3.19it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 65%|██████▍   | 104/161 [00:26<00:21,  2.69it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 65%|██████▌   | 105/161 [00:27<00:19,  2.92it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 66%|██████▌   | 106/161 [00:27<00:19,  2.82it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 66%|██████▋   | 107/161 [00:27<00:16,  3.20it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 67%|██████▋   | 108/161 [00:28<00:14,  3.57it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 68%|██████▊   | 109/161 [00:28<00:13,  3.86it/s]

  Erreur 2023 Grand Prix El Marsa.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 69%|██████▉   | 111/161 [00:28<00:12,  3.99it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 70%|██████▉   | 112/161 [00:28<00:11,  4.18it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 70%|███████   | 113/161 [00:29<00:12,  3.85it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 71%|███████   | 114/161 [00:29<00:11,  4.06it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 71%|███████▏  | 115/161 [00:29<00:12,  3.81it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 72%|███████▏  | 116/161 [00:29<00:11,  3.85it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 73%|███████▎  | 117/161 [00:30<00:11,  3.73it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 73%|███████▎  | 118/161 [00:30<00:12,  3.47it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 74%|███████▍  | 119/161 [00:30<00:12,  3.43it/s]

  Erreur 2024 Tour of Oman Stage 4.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)
  Erreur 2024 Tour of Oman Stage 5.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 76%|███████▌  | 122/161 [00:31<00:08,  4.81it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 76%|███████▋  | 123/161 [00:31<00:09,  4.02it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 77%|███████▋  | 124/161 [00:32<00:10,  3.42it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 78%|███████▊  | 125/161 [00:32<00:11,  3.17it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 78%|███████▊  | 126/161 [00:32<00:11,  3.13it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 79%|███████▉  | 127/161 [00:33<00:13,  2.53it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 80%|███████▉  | 128/161 [00:33<00:11,  2.81it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 80%|████████  | 129/161 [00:34<00:11,  2.78it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 81%|████████▏ | 131/161 [00:34<00:08,  3.70it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 82%|████████▏ | 132/161 [00:34<00:08,  3.42it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 83%|████████▎ | 133/161 [00:34<00:07,  3.74it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 84%|████████▍ | 135/161 [00:35<00:04,  5.64it/s]

  Erreur 2024 Kreiz Breizh Elites Stage 2.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 84%|████████▍ | 136/161 [00:35<00:04,  6.06it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 85%|████████▌ | 137/161 [00:35<00:03,  6.25it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 86%|████████▌ | 138/161 [00:35<00:05,  4.00it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 86%|████████▋ | 139/161 [00:36<00:04,  4.49it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 87%|████████▋ | 140/161 [00:36<00:05,  4.16it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 88%|████████▊ | 141/161 [00:36<00:05,  3.89it/s]

  Erreur 2024 Tre Valli Varesine.gpx : Error parsing XML: Specification mandates value for attribute async, line 161, column 15 (<string>, line 161)

/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 89%|████████▉ | 143/161 [00:36<00:03,  4.53it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 89%|████████▉ | 144/161 [00:37<00:03,  4.68it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 91%|█████████ | 146/161 [00:37<00:02,  5.75it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 91%|█████████▏| 147/161 [00:37<00:03,  4.11it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 92%|█████████▏| 148/161 [00:38<00:03,  4.33it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 93%|█████████▎| 149/161 [00:38<00:03,  3.27it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 93%|█████████▎| 150/161 [00:38<00:03,  3.38it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 94%|█████████▍| 151/161 [00:38<00:02,  3.95it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 94%|█████████▍| 152/161 [00:39<00:02,  4.41it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 95%|█████████▌| 153/161 [00:39<00:01,  4.85it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 96%|█████████▌| 154/161 [00:39<00:01,  5.10it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 96%|█████████▋| 155/161 [00:39<00:01,  5.02it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 97%|█████████▋| 156/161 [00:39<00:00,  5.44it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 98%|█████████▊| 157/161 [00:40<00:00,  4.51it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 98%|█████████▊| 158/161 [00:40<00:00,  4.28it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 99%|█████████▉| 159/161 [00:40<00:00,  4.98it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
 99%|█████████▉| 160/161 [00:40<00:00,  5.30it/s]/var/folders/w5/_dp1f8855qd_31v9b5ywhggh0000gn/T/ipykernel_67721/866117685.py:71: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  deniv_last = float(np.sum(d for d in np.diff(elevations[-last_pts:]) if d > 0))
100%|██████████| 161/161 [00:40<00:00,  3.93it/s]

Lignes mises a jour : 142
Lignes encore a 0 : 19
race_features.csv mis a jour

In [24]:
df_race = pd.read_csv(RACE_PATH)
mask = df_race['distance_gpx_km'] == 0
print(f'Lignes avec distance_gpx_km = 0 : {mask.sum()}')
df_race[mask][['course', 'year', 'stage_num', 'distance_gpx_km']].sort_values(['course', 'year'])

Lignes avec distance_gpx_km = 0 : 19

                                     course  year  stage_num  distance_gpx_km
1623                             africa-cup  2018        NaN              0.0
1622                         africa-cup-itt  2018        NaN              0.0
1621                         africa-cup-ttt  2018        NaN              0.0
4015  african-continental-championships-itt  2022        NaN              0.0
4009      african-cycling-championships-ttt  2022        NaN              0.0
5432                    grand-prix-el-marsa  2023        NaN              0.0
6209                    kreiz-breizh-elites  2024        2.0              0.0
2469                               nc-china  2019        NaN              0.0
3030                               nc-china  2020        NaN              0.0
2258                  nc-dominican-republic  2019        NaN              0.0
2274                             nc-georgia  2019        NaN              0.0
3727                        okolo-slovenska  2021        NaN              0.0
3361                      ronde-van-limburg  2021        NaN              0.0
353                            slag-om-norg  2017        NaN              0.0
3796                        ster-van-zwolle  2021        NaN              0.0
1616                         tour-of-fuzhou  2018        4.0              0.0
5675                           tour-of-oman  2024        4.0              0.0
5677                           tour-of-oman  2024        5.0              0.0
6424                     tre-valli-varesine  2024        NaN              0.0

In [25]:
df_race = pd.read_csv(RACE_PATH)
mask = df_race['distance_gpx_km'] == 0
print(f'Lignes supprimees : {mask.sum()}')
df_race = df_race[~mask]
print(f'Shape apres suppression : {df_race.shape}')
df_race.to_csv(RACE_PATH, index=False)
print('race_features.csv mis a jour')

Lignes supprimees : 19
Shape apres suppression : (7372, 41)
race_features.csv mis a jour