# Komoot Surface Scraper — par annee
Change juste ANNEE pour scraper une annee a la fois.

In [19]:
import os, time, json, re
import pandas as pd
from tqdm import tqdm
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

GPX_DIR     = '/Users/arthurdeletang/Desktop/Stage M1/Code/data/gpx_files_2'
OUTPUT_BASE = '/Users/arthurdeletang/Desktop/Stage M1/Code/data/matching'

In [20]:
ANNEE = 2025  # <-- change cette ligne pour chaque annee

CHECKPOINT = os.path.join(OUTPUT_BASE, 'all', f'komoot_checkpoint_all.json')
OUTPUT_CSV  = os.path.join(OUTPUT_BASE, 'all', f'komoot_surface_all.csv')

path = os.path.join(OUTPUT_BASE, 'all', f'matching_{ANNEE}.csv')
df_matching = pd.read_csv(path)
df_matching = df_matching[df_matching['statut'] == 'match']
gpx_all = df_matching['fichier_gpx'].dropna().unique().tolist()
print(f'{ANNEE} : {len(gpx_all)} courses')

results = []
already_done = set()
if os.path.exists(CHECKPOINT):
    with open(CHECKPOINT) as f:
        all_results = json.load(f)
    results = [r for r in all_results if r.get('route_url') and len(r) > 2]
    already_done = {r['fichier_gpx'] for r in results}
    echecs = [r['fichier_gpx'] for r in all_results if not r.get('route_url') or len(r) <= 2]
    print(f'Checkpoint : {len(already_done)} succes, {len(echecs)} echecs a re-essayer')

todo = [f for f in sorted(gpx_all) if f not in already_done]
print(f'Restant : {len(todo)}')

2025 : 906 courses
Checkpoint : 1837 succes, 6 echecs a re-essayer
Restant : 6

In [21]:
options = Options()
options.add_argument('--window-size=1440,900')
options.add_argument('--use-gl=swiftshader')
options.add_argument('--enable-unsafe-swiftshader')
options.add_argument('--enable-webgl')
options.add_argument('--ignore-gpu-blocklist')

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

driver.get('https://www.komoot.com/login')
print('Connecte-toi a Komoot, puis lance la cellule suivante.')

Connecte-toi a Komoot, puis lance la cellule suivante.

In [22]:
def find_gpx_path(fname, gpx_dir):
    full_path = os.path.join(gpx_dir, fname)
    if os.path.exists(full_path):
        return full_path
    # Essayer avec ' - ' au lieu de ' / '
    replaced = fname.replace(' / ', ' - ')
    repl_path = os.path.join(gpx_dir, replaced)
    if os.path.exists(repl_path):
        return repl_path
    # Essayer le nom tronque avant le '/'
    truncated = fname.split(' / ')[0].strip() + '.gpx'
    trunc_path = os.path.join(gpx_dir, truncated)
    if os.path.exists(trunc_path):
        return trunc_path
    return None

def wait_for_text(text, timeout=30):
    try:
        WebDriverWait(driver, timeout).until(
            lambda d: text in d.find_element(By.TAG_NAME, 'body').text
        )
        return True
    except Exception:
        return False

def parse_km(text):
    text = text.replace('\u00a0', ' ').strip()
    if '< 100' in text:
        return 0.0
    parts = text.split(' ')
    try:
        val = float(parts[0].replace(',', '.'))
        unit = parts[1] if len(parts) > 1 else 'km'
        return round(val / 1000 if unit == 'm' else val, 3)
    except Exception:
        return None

def upload_and_save(filepath):
    driver.get('https://www.komoot.com/upload')
    time.sleep(2)

    try:
        file_input = WebDriverWait(driver, 15).until(
            EC.presence_of_element_located((By.XPATH, "//input[@type='file']"))
        )
        driver.execute_script("arguments[0].style.display = 'block';", file_input)
        file_input.send_keys(filepath)
    except Exception as e:
        print(f'  Upload introuvable : {e}')
        return None

    # Attendre Import to Plan a Route OU erreur
    try:
        WebDriverWait(driver, 60).until(
            lambda d: 'Import to Plan a Route' in d.find_element(By.TAG_NAME, 'body').text
                      or "couldn't be imported" in d.find_element(By.TAG_NAME, 'body').text
                      or 'sorry' in d.find_element(By.TAG_NAME, 'body').text.lower()
        )
    except Exception:
        print('  Timeout attente dialogue')
        return None

    body = driver.find_element(By.TAG_NAME, 'body').text
    if "couldn't be imported" in body or 'sorry' in body.lower():
        print('  Fichier rejete par Komoot')
        return None

    if 'Import to Plan a Route' not in body:
        print('  Import dialog non detecte')
        return None

    # Etape 1 : Next
    driver.execute_script("document.querySelectorAll('a[aria-label=\"Next\"]')[0]?.click();")
    print('  Etape 1 clic Next')

    if not wait_for_text('Road cycling', timeout=30):
        print('  Page Sport non detectee')
        return None
    print('  Etape 1 OK -> Page Sport')

    # Etape 2 : Next
    driver.execute_script("document.querySelectorAll('a[aria-label=\"Next\"]')[0]?.click();")
    print('  Etape 2 clic Next')

    # Attendre Resolve Routing OU Route matches OU Route deviates OU Route Saved
    try:
        WebDriverWait(driver, 30).until(
            lambda d: 'Resolve Routing' in d.find_element(By.TAG_NAME, 'body').text
                      or 'Route matches to known ways' in d.find_element(By.TAG_NAME, 'body').text
                      or 'Route deviates from known ways' in d.find_element(By.TAG_NAME, 'body').text
                      or 'Route Saved' in d.find_element(By.TAG_NAME, 'body').text
        )
    except Exception:
        print('  Aucune page intermediaire detectee')
        print('  Body:', driver.find_element(By.TAG_NAME, 'body').text[:300])
        return None

    body = driver.find_element(By.TAG_NAME, 'body').text

    if 'Resolve Routing' in body or 'Route matches to known ways' in body or 'Route deviates from known ways' in body:
        if 'Resolve Routing' in body:
            print('  Resolve Routing detecte')
        elif 'Route deviates from known ways' in body:
            print('  Route deviates detecte')
        else:
            print('  Route matches detecte')
        driver.execute_script("document.querySelectorAll('a[aria-label=\"Save\"]')[0]?.click();")
        print('  Etape 3 clic Save')
        if not wait_for_text('Route Saved', timeout=30):
            print('  Route Saved non detecte apres Save')
            return None

    print('  Route Saved OK')
    driver.execute_script("document.querySelectorAll('a.css-zi6wow')[0]?.click();")

    try:
        WebDriverWait(driver, 15).until(lambda d: '/tour/' in d.current_url)
    except Exception:
        print('  URL /tour/ non detectee')
        return None

    time.sleep(1)
    return driver.current_url


def scrape_surface(route_url):
    driver.get(route_url)
    try:
        WebDriverWait(driver, 15).until(
            lambda d: len(d.find_elements(By.CSS_SELECTOR, 'div.css-esdg3g')) > 0
        )
    except Exception:
        print('  Section Way Types non chargee')
        return {}
    driver.execute_script('window.scrollTo(0, document.body.scrollHeight / 2);')
    time.sleep(1)
    entry = {}
    try:
        rows = driver.find_elements(By.CSS_SELECTOR, 'div.css-esdg3g')
        for row in rows:
            try:
                label_el = row.find_element(By.CSS_SELECTOR, 'button.css-1xu3avq')
                value_el = row.find_element(By.CSS_SELECTOR, 'p.css-1wxtat5')
                label = label_el.text.strip().rstrip(':').lower().replace(' ', '_')
                if not label:
                    continue
                entry[f'{label}_km'] = parse_km(value_el.text)
            except Exception:
                continue
    except Exception as e:
        print(f'  scrape_surface : {e}')
    return entry


def save_checkpoint():
    tmp = CHECKPOINT + '.tmp'
    with open(tmp, 'w') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    os.replace(tmp, CHECKPOINT)

print('Fonctions chargees.')

Fonctions chargees.

In [23]:
for idx, fname in enumerate(tqdm(todo)):
    filepath = find_gpx_path(fname, GPX_DIR)
    entry = {'fichier_gpx': fname}

    if not filepath:
        print(f'  Fichier introuvable : {fname}')
        results.append(entry)
        save_checkpoint()
        continue

    route_url = None
    try:
        route_url = upload_and_save(filepath)
    except Exception as e:
        print(f'  Exception : {e}')

    if route_url:
        entry['route_url'] = route_url
        entry.update(scrape_surface(route_url))
        print(f'  OK : {fname}')
    else:
        print(f'  ECHEC FINAL : {fname}')

    results.append(entry)
    save_checkpoint()

print('Termine.')
pd.DataFrame(results)

  0%|          | 0/6 [00:00<?, ?it/s]

  Fichier introuvable : 2025 GP Vorarlberg p/b Radhaus Rankweil.gpx
  Etape 1 clic Next
  Etape 1 OK -> Page Sport
  Etape 2 clic Next
  Route matches detecte
  Etape 3 clic Save
  Route Saved OK

 33%|███▎      | 2/6 [00:48<01:37, 24.39s/it]

  OK : 2025 Lidl Deutschland Tour Prologue.gpx
  Etape 1 clic Next
  Etape 1 OK -> Page Sport
  Etape 2 clic Next
  Resolve Routing detecte
  Etape 3 clic Save
  Route Saved OK

 50%|█████     | 3/6 [01:17<01:18, 26.04s/it]

  OK : 2025 Renewi Tour Stage 1.gpx
  Etape 1 clic Next
  Etape 1 OK -> Page Sport
  Etape 2 clic Next
  Resolve Routing detecte
  Etape 3 clic Save
  Route Saved OK

 67%|██████▋   | 4/6 [01:56<01:02, 31.02s/it]

  OK : 2025 Tour Bitwa Warszawska Stage 1.gpx
  Etape 1 clic Next
  Etape 1 OK -> Page Sport
  Etape 2 clic Next
  Resolve Routing detecte
  Etape 3 clic Save
  Route Saved OK

 83%|████████▎ | 5/6 [02:19<00:28, 28.34s/it]

  OK : 2025 Tour du Limousin-Perigord - Nouvelle Aquitaine Stage 1.gpx
  Etape 1 clic Next
  Etape 1 OK -> Page Sport
  Etape 2 clic Next
  Resolve Routing detecte
  Etape 3 clic Save
  Route Saved OK

100%|██████████| 6/6 [02:40<00:00, 26.81s/it]

  OK : 2025 Tour du Limousin-Perigord - Nouvelle Aquitaine Stage 2.gpx
Termine.

,fichier_gpx,route_url,road_km,cycleway_km,street_km,unknown_km,state_road_km,off-grid_(unknown)_km,path_km,singletrack_km,asphalt_km,paved_km,cobblestones_km,unpaved_km,compacted_gravel_km,access_road_km,alpine_km
0,2025 ADAC Cyclassics.gpx,https://www.komoot.com/tour/2950103693,104.0,59.30,23.000,3.010,5.810,2.850,0.611,0.356,171.00,30.80,2.68,0.403,NaN,NaN,NaN
1,2025 Amstel Gold Race.gpx,https://www.komoot.com/tour/2950105131,121.0,82.50,7.270,5.830,0.852,5.380,0.278,0.198,225.00,18.80,6.78,0.210,NaN,NaN,NaN
2,2025 Bretagne Classic - CIC.gpx,https://www.komoot.com/tour/2950106378,238.0,1.43,7.280,0.569,14.500,0.569,NaN,NaN,202.00,59.10,NaN,NaN,NaN,NaN,NaN
3,2025 Cadel Evans Great Ocean Road Race.gpx,https://www.komoot.com/tour/2950107577,103.0,29.30,3.920,0.504,4.410,0.504,0.000,NaN,94.30,46.80,NaN,NaN,NaN,NaN,NaN
4,2025 Classic Brugge-De Panne.gpx,https://www.komoot.com/tour/2950108889,70.1,66.70,31.800,0.757,9.750,NaN,0.357,0.731,142.00,47.60,5.24,0.731,0.321,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1838,2025 Lidl Deutschland Tour Prologue.gpx,https://www.komoot.com/tour/3006735169,NaN,1.36,1.630,NaN,NaN,NaN,NaN,NaN,2.99,NaN,NaN,NaN,NaN,NaN,NaN
1839,2025 Renewi Tour Stage 1.gpx,https://www.komoot.com/tour/3006736499,58.1,45.60,8.120,16.400,0.000,13.000,1.870,0.776,136.00,24.90,6.29,0.795,0.436,0.163,NaN
1840,2025 Tour Bitwa Warszawska Stage 1.gpx,https://www.komoot.com/tour/3006737333,143.0,NaN,28.300,NaN,NaN,NaN,NaN,NaN,168.00,3.33,NaN,NaN,NaN,NaN,NaN
1841,2025 Tour du Limousin-Perigord - Nouvelle Aqui...,https://www.komoot.com/tour/3006738700,180.0,NaN,0.564,NaN,3.900,NaN,NaN,NaN,174.00,9.88,NaN,NaN,NaN,NaN,NaN
1842,2025 Tour du Limousin-Perigord - Nouvelle Aqui...,https://www.komoot.com/tour/3006739548,168.0,0.00,3.060,NaN,2.200,NaN,NaN,NaN,125.00,47.60,NaN,NaN,NaN,NaN,NaN

In [24]:
driver.quit()
df_komoot = pd.DataFrame(results).fillna(0)
df_komoot.to_csv(OUTPUT_CSV, index=False)
print(f'Sauvegarde : {OUTPUT_CSV}')
print(f'Shape : {df_komoot.shape}')
df_komoot

Sauvegarde : /Users/arthurdeletang/Desktop/Stage M1/Code/data/matching/all/komoot_surface_all.csv
Shape : (1843, 17)

,fichier_gpx,route_url,road_km,cycleway_km,street_km,unknown_km,state_road_km,off-grid_(unknown)_km,path_km,singletrack_km,asphalt_km,paved_km,cobblestones_km,unpaved_km,compacted_gravel_km,access_road_km,alpine_km
0,2025 ADAC Cyclassics.gpx,https://www.komoot.com/tour/2950103693,104.0,59.30,23.000,3.010,5.810,2.850,0.611,0.356,171.00,30.80,2.68,0.403,0.000,0.000,0.0
1,2025 Amstel Gold Race.gpx,https://www.komoot.com/tour/2950105131,121.0,82.50,7.270,5.830,0.852,5.380,0.278,0.198,225.00,18.80,6.78,0.210,0.000,0.000,0.0
2,2025 Bretagne Classic - CIC.gpx,https://www.komoot.com/tour/2950106378,238.0,1.43,7.280,0.569,14.500,0.569,0.000,0.000,202.00,59.10,0.00,0.000,0.000,0.000,0.0
3,2025 Cadel Evans Great Ocean Road Race.gpx,https://www.komoot.com/tour/2950107577,103.0,29.30,3.920,0.504,4.410,0.504,0.000,0.000,94.30,46.80,0.00,0.000,0.000,0.000,0.0
4,2025 Classic Brugge-De Panne.gpx,https://www.komoot.com/tour/2950108889,70.1,66.70,31.800,0.757,9.750,0.000,0.357,0.731,142.00,47.60,5.24,0.731,0.321,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1838,2025 Lidl Deutschland Tour Prologue.gpx,https://www.komoot.com/tour/3006735169,0.0,1.36,1.630,0.000,0.000,0.000,0.000,0.000,2.99,0.00,0.00,0.000,0.000,0.000,0.0
1839,2025 Renewi Tour Stage 1.gpx,https://www.komoot.com/tour/3006736499,58.1,45.60,8.120,16.400,0.000,13.000,1.870,0.776,136.00,24.90,6.29,0.795,0.436,0.163,0.0
1840,2025 Tour Bitwa Warszawska Stage 1.gpx,https://www.komoot.com/tour/3006737333,143.0,0.00,28.300,0.000,0.000,0.000,0.000,0.000,168.00,3.33,0.00,0.000,0.000,0.000,0.0
1841,2025 Tour du Limousin-Perigord - Nouvelle Aqui...,https://www.komoot.com/tour/3006738700,180.0,0.00,0.564,0.000,3.900,0.000,0.000,0.000,174.00,9.88,0.00,0.000,0.000,0.000,0.0
1842,2025 Tour du Limousin-Perigord - Nouvelle Aqui...,https://www.komoot.com/tour/3006739548,168.0,0.00,3.060,0.000,2.200,0.000,0.000,0.000,125.00,47.60,0.00,0.000,0.000,0.000,0.0

In [25]:
import pandas as pd
import os

OUTPUT_BASE = '/Users/arthurdeletang/Desktop/Stage M1/Code/data/matching'

manquants = []
for year in range(2017, 2026):
    path = os.path.join(OUTPUT_BASE, 'all', f'matching_{year}.csv')
    if os.path.exists(path):
        df = pd.read_csv(path)
        df = df[df['statut'] == 'match']
        m = df[df['fichier_gpx'].str.contains(' / ', na=False)]['fichier_gpx'].unique()
        if len(m) > 0:
            print(f'{year} : {len(m)} fichiers manquants')
            manquants.extend(m)

print(f'\nTotal : {len(manquants)} fichiers avec / dans le nom')

2017 : 10 fichiers manquants
2018 : 17 fichiers manquants
2019 : 16 fichiers manquants
2020 : 1 fichiers manquants
2021 : 15 fichiers manquants
2022 : 19 fichiers manquants
2023 : 14 fichiers manquants
2024 : 17 fichiers manquants
2025 : 18 fichiers manquants

Total : 127 fichiers avec / dans le nom

In [26]:
import os, json
import pandas as pd

OUTPUT_BASE = '/Users/arthurdeletang/Desktop/Stage M1/Code/data/matching'

# Charger tous les checkpoints
all_results = []

# 2017-2023 : un fichier par année
for year in range(2017, 2024):
    path = os.path.join(OUTPUT_BASE, 'all', f'komoot_checkpoint_{year}.json')
    if os.path.exists(path):
        with open(path) as f:
            data = json.load(f)
        succes = [r for r in data if r.get('route_url') and len(r) > 2]
        all_results.extend(succes)
        print(f'{year} : {len(succes)} succes')

# 2024-2025 : fichier commun
path_all = os.path.join(OUTPUT_BASE, 'all', 'komoot_checkpoint_all.json')
if os.path.exists(path_all):
    with open(path_all) as f:
        data = json.load(f)
    succes = [r for r in data if r.get('route_url') and len(r) > 2]
    all_results.extend(succes)
    print(f'2024-2025 : {len(succes)} succes')

# Dedupliquer sur fichier_gpx
df_komoot = pd.DataFrame(all_results)
df_komoot = df_komoot.drop_duplicates(subset='fichier_gpx', keep='last')
print(f'\nTotal unique : {len(df_komoot)} courses')
print(f'Colonnes : {list(df_komoot.columns)}')

2017 : 583 succes
2018 : 1016 succes
2019 : 1044 succes
2020 : 444 succes
2021 : 693 succes
2022 : 804 succes
2023 : 917 succes
2024-2025 : 1842 succes

Total unique : 7343 courses
Colonnes : ['fichier_gpx', 'route_url', 'road_km', 'street_km', 'state_road_km', 'cycleway_km', 'off-grid_(unknown)_km', 'access_road_km', 'asphalt_km', 'paved_km', 'cobblestones_km', 'unknown_km', 'path_km', 'unpaved_km', 'singletrack_km', 'compacted_gravel_km', '_km', 'alpine_km', 'ferry_km', 'alpine_path_km']

In [27]:
# Sauvegarder le CSV Komoot fusionné
output_path = os.path.join(OUTPUT_BASE, 'all', 'komoot_surface_all.csv')
df_komoot.to_csv(output_path, index=False)
print(f'Sauvegarde : {output_path}')
print(f'Shape : {df_komoot.shape}')

Sauvegarde : /Users/arthurdeletang/Desktop/Stage M1/Code/data/matching/all/komoot_surface_all.csv
Shape : (7343, 20)

In [28]:
import os
gpx_dir = "/Users/arthurdeletang/Desktop/Stage M1/Code/data/gpx_files_2"
files_2025 = [f for f in os.listdir(gpx_dir) if f.startswith("2025")]
print(sorted(files_2025))

['2025 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 1.gpx', '2025 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 2.gpx', '2025 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 3.gpx', '2025 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 4.gpx', '2025 4 Jours de Dunkerque - Grand Prix des Hauts de France Stage 5.gpx', '2025 4 Jours de Dunkerque .gpx', '2025 A Travers les Hauts de France.gpx', '2025 ADAC Cyclassics.gpx', '2025 Ain Bugey Valromey Tour Stage 1.gpx', '2025 Ain Bugey Valromey Tour Stage 2.gpx', '2025 Ain Bugey Valromey Tour Stage 3.gpx', '2025 Ain Bugey Valromey Tour Stage 4.gpx', '2025 Ain Bugey Valromey Tour Stage 5.gpx', '2025 AlUla Tour Stage 1.gpx', '2025 AlUla Tour Stage 2.gpx', '2025 AlUla Tour Stage 3.gpx', '2025 AlUla Tour Stage 4.gpx', '2025 AlUla Tour Stage 5.gpx', '2025 Alpes Gresivaudan Classic.gpx', '2025 Alpes Isere Tour Stage 1.gpx', '2025 Alpes Isere Tour Stage 2.gpx', '2025 Alpes Isere Tour Stage 3.gpx', '2025 Alpes Isere Tour Stage 4.gpx', '2025 Alpes Isere Tour Stage 5.gpx', '2025 Amstel Gold Race Ladies Edition.gpx', '2025 Amstel Gold Race.gpx', '2025 Andorra Morabanc Classica.gpx', '2025 Antwerp Port Epic - Sels Trophy.gpx', '2025 Antwerp Port Epic .gpx', '2025 Antwerp Port Epic Ladies.gpx', '2025 Arctic Race of Norway Stage 1.gpx', '2025 Arctic Race of Norway Stage 2.gpx', '2025 Arctic Race of Norway Stage 3.gpx', '2025 Arctic Race of Norway Stage 4.gpx', '2025 Argenta Classic - Deurne.gpx', '2025 Arno Wallaard Memorial.gpx', '2025 Asian Road Cycling Championships - ITT.gpx', '2025 Asian Road Cycling Championships - Mixed Relay.gpx', '2025 Asian Road Cycling Championships.gpx', '2025 Aubel-Thimister-Stavelot Stage 1.gpx', '2025 Aubel-Thimister-Stavelot Stage 2-1.gpx', '2025 Aubel-Thimister-Stavelot Stage 2-2.gpx', '2025 Aubel-Thimister-Stavelot Stage 3.gpx', '2025 Australian Road National Championships - Criterium.gpx', '2025 Australian Road National Championships - ITT.gpx', '2025 Australian Road National Championships.gpx', '2025 Austrian Road National Championship.gpx', '2025 Austrian Road National Championships.gpx', '2025 Baloise Belgium Tour Stage 1.gpx', '2025 Baloise Belgium Tour Stage 2.gpx', '2025 Baloise Belgium Tour Stage 3.gpx', '2025 Baloise Belgium Tour Stage 4.gpx', '2025 Baloise Belgium Tour Stage 5.gpx', '2025 Baloise Ladies Tour Prologue.gpx', '2025 Baloise Ladies Tour Stage 1.gpx', '2025 Baloise Ladies Tour Stage 2.gpx', '2025 Baloise Ladies Tour Stage 3-1.gpx', '2025 Baloise Ladies Tour Stage 3-2.gpx', '2025 Baloise Ladies Tour Stage 4.gpx', '2025 Baltic Chain Tour Stage 1-1.gpx', '2025 Baltic Chain Tour Stage 1-2.gpx', '2025 Baltic Chain Tour Stage 2.gpx', '2025 Baltic Chain Tour Stage 3.gpx', '2025 Belgian Road National Championship.gpx', '2025 Belgian Road National Championships - ITT.gpx', '2025 Belgrade Banjaluka Stage 1.gpx', '2025 Belgrade Banjaluka Stage 2.gpx', '2025 Belgrade Banjaluka Stage 3.gpx', '2025 Belgrade Banjaluka Stage 4.gpx', '2025 Bernaudeau Junior.gpx', '2025 Bestronics Acht van Blade Stage 1.gpx', '2025 Bestronics Acht van Blade Stage 2.gpx', '2025 Bestronics Acht van Blade Stage 3-1.gpx', '2025 Bestronics Acht van Blade Stage 3-2.gpx', '2025 Binche - Chimay - Binche - Memorial Frank Vandenbroucke.gpx', '2025 Binche - Chimay - Binche .gpx', '2025 Binche - Chimay - Binche pour Dames.gpx', '2025 Bizkaikoloreak Stage 1.gpx', '2025 Bizkaikoloreak Stage 2.gpx', "2025 Boucle de l'Artois.gpx", "2025 Boucles de l'Aulne - Chateaulin.gpx", "2025 Boucles de l'Oise Juniors Stage 1.gpx", "2025 Boucles de l'Oise Juniors Stage 2-1.gpx", "2025 Boucles de l'Oise Juniors Stage 2-2.gpx", '2025 Boucles de la Mayenne - Credit Mutuel Prologue.gpx', '2025 Boucles de la Mayenne - Credit Mutuel Stage 1.gpx', '2025 Boucles de la Mayenne - Credit Mutuel Stage 2.gpx', '2025 Boucles de la Mayenne - Credit Mutuel Stage 3.gpx', '2025 Bredene Koksijde Classic.gpx', '2025 Bretagne Classic - CIC.gpx', '2025 British Road National Championship - ITT.gpx', '2025 British Road National Championship.gpx', '2025 Brussels Cycling Classic.gpx', '2025 CAC African Road Championships - ITT.gpx', '2025 CAC African Road Championships - Mixed Relay TTT.gpx', '2025 CAC African Road Championships.gpx', '2025 CIC Tour de la Provence Stage 1.gpx', '2025 CIC Tour de la Provence Stage 2.gpx', '2025 CIC Tour de la Provence Stage 3.gpx', '2025 COPACI Campeonato Panamericano de Ruta - ITT.gpx', '2025 COPACI Campeonato Panamericano de Ruta.gpx', '2025 Cadel Evans Great Ocean Road Race.gpx', '2025 Canadian Road National Championships - ITT.gpx', '2025 Canadian Road National Championships.gpx', '2025 Caribbean Elite Road Cycling Championships - ITT.gpx', '2025 Caribbean Elite Road Cycling Championships.gpx', '2025 Cavaliere Liberazione Junior.gpx', '2025 Cholet Agglo Tour.gpx', '2025 Chrono Feminin de Gatineau.gpx', '2025 Chrono des Nations.gpx', '2025 Circuit Franco-Belge.gpx', '2025 Circuit des Ardennes Stage 1.gpx', '2025 Circuit des Ardennes Stage 2.gpx', '2025 Circuit des Ardennes Stage 3.gpx', '2025 Circuit des Ardennes Stage 4.gpx', '2025 Circuit des Ardennes Stage 5.gpx', '2025 Circuito de Getxo - Memorial Hermanos Otxoa.gpx', '2025 Circuito del Porto - Trofeo Arvedi.gpx', '2025 Clasica Ciclista Internacional a Castilla y Leon.gpx', "2025 Clasica Jaen - Nation's Cup Women.gpx", '2025 Clasica Jaen - Paraiso Interior.gpx', '2025 Clasica de Almeria.gpx', '2025 Classic Brugge-De Panne.gpx', '2025 Classic Grand Besancon Doubs.gpx', '2025 Classic Lorient Agglomeration - Ceratizit.gpx', '2025 Classic Region Sud U19 - Hautes-Alpes - Super Devoluy.gpx', '2025 Classic Region Sud U19 - Montagne de Lure.gpx', '2025 Classic Var.gpx', '2025 Classica Camp de Morvedre.gpx', '2025 Classica Comunitat Valenciana 1969 - Gran Premi Valencia.gpx', "2025 Classica Terres de l'Ebre.gpx", '2025 Classique Dunkerque - Grand prix des Hauts de France.gpx', '2025 Classique Dunkerque .gpx', '2025 Copenhagen Sprint.gpx', '2025 Coppa Agostoni - Giro delle Brianze.gpx', '2025 Coppa Bernocchi - GP Banco BPM.gpx', '2025 Coppa Citta di San Daniele.gpx', '2025 Coppa Montes Gran Premio della Resistenza.gpx', '2025 Coppa della Pace - Trofeo Fratelli Anelli.gpx', "2025 Cote d'Or Classic Juniors Stage 1-1.gpx", "2025 Cote d'Or Classic Juniors Stage 1-2.gpx", "2025 Cote d'Or Classic Juniors Stage 2.gpx", '2025 Course Cycliste de Solidarnosc et des Champions Olympiques Stage 1-1.gpx', '2025 Course Cycliste de Solidarnosc et des Champions Olympiques Stage 1-2.gpx', '2025 Course Cycliste de Solidarnosc et des Champions Olympiques Stage 2.gpx', '2025 Course Cycliste de Solidarnosc et des Champions Olympiques Stage 3.gpx', '2025 Course Cycliste de Solidarnosc et des Champions Olympiques Stage 4.gpx', '2025 Course de la Paix Grand Prix Jeseniky Stage 1.gpx', '2025 Course de la Paix Grand Prix Jeseniky Stage 2.gpx', '2025 Course de la Paix Grand Prix Jeseniky Stage 3.gpx', '2025 Course de la Paix Grand Prix Jeseniky Stage 4.gpx', '2025 Course de la Paix Juniors Stage 1.gpx', '2025 Course de la Paix Juniors Stage 2-1.gpx', '2025 Course de la Paix Juniors Stage 2-2.gpx', '2025 Course de la Paix Juniors Stage 3.gpx', '2025 Course de la Paix Juniors Stage 4.gpx', '2025 Criterium du Dauphine Stage 1.gpx', '2025 Criterium du Dauphine Stage 2.gpx', '2025 Criterium du Dauphine Stage 3.gpx', '2025 Criterium du Dauphine Stage 4.gpx', '2025 Criterium du Dauphine Stage 5.gpx', '2025 Criterium du Dauphine Stage 6.gpx', '2025 Criterium du Dauphine Stage 7.gpx', '2025 Criterium du Dauphine Stage 8.gpx', '2025 Cro Race Stage 1.gpx', '2025 Cro Race Stage 2.gpx', '2025 Cro Race Stage 3.gpx', '2025 Cro Race Stage 4.gpx', '2025 Cro Race Stage 5.gpx', '2025 Cro Race Stage 6.gpx', '2025 Cycling Tour of Albania Stage 1.gpx', '2025 Cycling Tour of Albania Stage 2.gpx', '2025 Cycling Tour of Albania Stage 3.gpx', '2025 Cycling Tour of Albania Stage 4.gpx', '2025 Cycling Tour of Albania Stage 5.gpx', '2025 Czech Republic Road National Championship - ITT.gpx', '2025 Czech Republic Road National Championship.gpx', '2025 Czech Tour Stage 1.gpx', '2025 Czech Tour Stage 2.gpx', '2025 Czech Tour Stage 3.gpx', '2025 Czech Tour Stage 4.gpx', '2025 Danilith Nokere Koerse MJ.gpx', '2025 Danilith Nokere Koerse WE.gpx', '2025 Danilith Nokere Koerse.gpx', '2025 Danish Road National Championship - ITT.gpx', '2025 Danish Road National Championship.gpx', '2025 De Brabantse Pijl - La Fleche Brabanconne.gpx', '2025 Dhofar Classic.gpx', '2025 Donostia San Sebastian Klasikoa.gpx', '2025 Dookola Mazowsza Stage 1.gpx', '2025 Dookola Mazowsza Stage 2.gpx', '2025 Dookola Mazowsza Stage 3.gpx', '2025 Dookola Mazowsza Stage 4.gpx', '2025 Dorpenomloop Rucphen.gpx', '2025 Druivenkoers - Overijse.gpx', '2025 Due Giorni Marchigiana - G.P. Santa Rita.gpx', '2025 Due Giorni Marchigiana - Trofeo Citta di Castelfidardo.gpx', '2025 Duracell Dwars door het Hageland.gpx', '2025 Durango - Durango Emakumeen Saria.gpx', '2025 Dutch Road National Championship - ITT.gpx', '2025 Dutch Road National Championship.gpx', '2025 Dwars door Vlaanderen - A travers la Flandre.gpx', '2025 Dwars door de Westhoek.gpx', '2025 Dwars door het Hageland.gpx', '2025 E3 Saxo Classic.gpx', '2025 Egmont Cycling Race Women.gpx', '2025 Elfstedenronde Brugge.gpx', '2025 Elite Road Central American Championships - ITT.gpx', '2025 Elite Road Central American Championships - TTT.gpx', '2025 Elite Road Central American Championships.gpx', '2025 Ename Samyn Classic.gpx', '2025 Eroica Juniores - Coppa Andrea Meneghelli.gpx', '2025 Eschborn-Frankfurt U23.gpx', '2025 Eschborn-Frankfurt.gpx', '2025 Estonian Road National Championships - ITT.gpx', '2025 Estonian Road National Championships.gpx', '2025 Ethias Tour de Wallonie Stage 1.gpx', '2025 Ethias Tour de Wallonie Stage 2.gpx', '2025 Ethias Tour de Wallonie Stage 3.gpx', '2025 Ethias Tour de Wallonie Stage 4.gpx', '2025 Ethias Tour de Wallonie Stage 5.gpx', '2025 Etoile de Besseges - Tour du Gard Stage 1.gpx', '2025 Etoile de Besseges - Tour du Gard Stage 2.gpx', '2025 Etoile de Besseges - Tour du Gard Stage 3.gpx', '2025 Etoile de Besseges - Tour du Gard Stage 4.gpx', '2025 Etoile de Besseges - Tour du Gard Stage 5.gpx', '2025 Faun Drome Classic.gpx', '2025 Faun-Ardeche Classic.gpx', '2025 Fenix Omloop van het Hageland.gpx', '2025 Festival Elsy Jacobs a Garnich.gpx', '2025 Festival Elsy Jacobs a Luxembourg.gpx', '2025 Figueira Champions Classic.gpx', '2025 Fleche Ardennaise.gpx', '2025 Fleche du Sud Prologue.gpx', '2025 Fleche du Sud Stage 1.gpx', '2025 Fleche du Sud Stage 2.gpx', '2025 Fleche du Sud Stage 3.gpx', '2025 Fleche du Sud Stage 4.gpx', '2025 French Road National Championship - ITT.gpx', '2025 French Road National Championship.gpx', '2025 Fyn Rundt - Tour of Funen.gpx', '2025 G.P. F.W.R. BARON - Pieve del Grappa - Possagno Stage 1-1.gpx', '2025 G.P. F.W.R. BARON - Pieve del Grappa - Possagno Stage 1-2.gpx', '2025 G.P. F.W.R. BARON - Pieve del Grappa - Possagno Stage 2.gpx', '2025 G.P. Palio del Recioto - Trofeo Zanotti Mobili.gpx', '2025 GP Adria Mobil.gpx', '2025 GP Brda-Collio.gpx', '2025 GP Capodarco Comunita Di Capodarco.gpx', '2025 GP General Patton.gpx', '2025 GP Immo Zone.gpx', '2025 GP Industria & Artigianato.gpx', '2025 GP Internacional Torres Vedras - Trofeu Joaquim Agostinho Prologue.gpx', '2025 GP Internacional Torres Vedras - Trofeu Joaquim Agostinho Stage 1.gpx', '2025 GP Internacional Torres Vedras - Trofeu Joaquim Agostinho Stage 2.gpx', '2025 GP Internacional Torres Vedras - Trofeu Joaquim Agostinho Stage 3.gpx', '2025 GP Kranj.gpx', '2025 GP Lucien Van Impe.gpx', '2025 GP Mazda Schelkens.gpx', '2025 GP Plouay Junior Men.gpx', '2025 GP Rik Van Looy.gpx', '2025 GP Slovenian Istria.gpx', '2025 GP Syedra Ancient City.gpx', '2025 GP Vorarlberg p.gpx', '2025 GP de Fourmies - La Voix du Nord.gpx', '2025 GP de Fourmies .gpx', '2025 Gent-Wevelgem .gpx', '2025 Gent-Wevelgem in Flanders Fields.gpx', '2025 Gent-Wevelgem.gpx', '2025 German Road National Championship - ITT.gpx', '2025 German Road National Championship.gpx', '2025 Gipuzkoa Klasikoa Stage 1.gpx', '2025 Gipuzkoa Klasikoa Stage 2.gpx', "2025 Giro Ciclistico della Valle d'Aosta - Mont Blanc Stage 1.gpx", "2025 Giro Ciclistico della Valle d'Aosta - Mont Blanc Stage 3.gpx", "2025 Giro Ciclistico della Valle d'Aosta - Mont Blanc Stage 4.gpx", "2025 Giro Ciclistico della Valle d'Aosta - Mont Blanc Stage 5.gpx", "2025 Giro Ciclistico della Valle d'Aosta - Mont Blanc.gpx", '2025 Giro Himledalen.gpx', '2025 Giro Mediterraneo in Rosa Stage 1.gpx', '2025 Giro Mediterraneo in Rosa Stage 2.gpx', '2025 Giro Mediterraneo in Rosa Stage 3.gpx', "2025 Giro d'Italia Next Gen Stage 1.gpx", "2025 Giro d'Italia Next Gen Stage 2.gpx", "2025 Giro d'Italia Next Gen Stage 3.gpx", "2025 Giro d'Italia Next Gen Stage 4.gpx", "2025 Giro d'Italia Next Gen Stage 5.gpx", "2025 Giro d'Italia Next Gen Stage 6.gpx", "2025 Giro d'Italia Next Gen Stage 7.gpx", "2025 Giro d'Italia Next Gen Stage 8.gpx", "2025 Giro d'Italia Rest day.gpx", "2025 Giro d'Italia Stage 1.gpx", "2025 Giro d'Italia Stage 10.gpx", "2025 Giro d'Italia Stage 11.gpx", "2025 Giro d'Italia Stage 12.gpx", "2025 Giro d'Italia Stage 13.gpx", "2025 Giro d'Italia Stage 14.gpx", "2025 Giro d'Italia Stage 15.gpx", "2025 Giro d'Italia Stage 16.gpx", "2025 Giro d'Italia Stage 17.gpx", "2025 Giro d'Italia Stage 18.gpx", "2025 Giro d'Italia Stage 19.gpx", "2025 Giro d'Italia Stage 2.gpx", "2025 Giro d'Italia Stage 20.gpx", "2025 Giro d'Italia Stage 21.gpx", "2025 Giro d'Italia Stage 3.gpx", "2025 Giro d'Italia Stage 4.gpx", "2025 Giro d'Italia Stage 5.gpx", "2025 Giro d'Italia Stage 6.gpx", "2025 Giro d'Italia Stage 7.gpx", "2025 Giro d'Italia Stage 8.gpx", "2025 Giro d'Italia Stage 9.gpx", "2025 Giro d'Italia Women Stage 1.gpx", "2025 Giro d'Italia Women Stage 2.gpx", "2025 Giro d'Italia Women Stage 3.gpx", "2025 Giro d'Italia Women Stage 4.gpx", "2025 Giro d'Italia Women Stage 5.gpx", "2025 Giro d'Italia Women Stage 6.gpx", "2025 Giro d'Italia Women Stage 7.gpx", "2025 Giro d'Italia Women Stage 8.gpx", '2025 Giro del Belvedere.gpx', '2025 Giro del Medio Brenta.gpx', '2025 Giro del Veneto.gpx', "2025 Giro dell'Appennino Donne Elite.gpx", "2025 Giro dell'Appennino.gpx", "2025 Giro dell'Emilia Internazionale Donne Elite.gpx", "2025 Giro dell'Emilia.gpx", '2025 Giro della Citta Metropolitana di Reggio Calabria.gpx', '2025 Giro della Lunigiana Stage 1.gpx', '2025 Giro della Lunigiana Stage 2.gpx', '2025 Giro della Lunigiana Stage 3-1.gpx', '2025 Giro della Lunigiana Stage 3-2.gpx', '2025 Giro della Lunigiana Stage 4.gpx', '2025 Giro della Provincia di Biella - Torino-Biella.gpx', '2025 Giro della Regione Friuli Venezia Giulia Stage 1.gpx', '2025 Giro della Regione Friuli Venezia Giulia Stage 2.gpx', '2025 Giro della Regione Friuli Venezia Giulia Stage 4.gpx', '2025 Giro della Regione Friuli Venezia Giulia.gpx', '2025 Giro della Romagna.gpx', '2025 Giro della Toscana - Memorial Alfredo Martini.gpx', '2025 Giro di Primavera.gpx', '2025 Gracia Stage 1.gpx', '2025 Gracia Stage 2.gpx', '2025 Gracia Stage 3-1.gpx', '2025 Gracia Stage 3-2.gpx', '2025 Gracia Stage 4.gpx', '2025 Gran Piemonte.gpx', '2025 Gran Premi Les Franqueses KH7.gpx', '2025 Gran Premio Castellon - Ruta de la Ceramica.gpx', '2025 Gran Premio Citta di Peccioli - Coppa Sabatini.gpx', '2025 Gran Premio Ciudad de Eibar.gpx', '2025 Gran Premio Industrie del Marmo.gpx', '2025 Gran Premio Miguel Indurain.gpx', '2025 Gran Premio New York City.gpx', '2025 Gran Premio San Vicente - Costa Blanca - Junior C.R.I..gpx', '2025 Gran Premio San Vicente - Costa Blanca - Junior Ruta.gpx', '2025 Gran Premio Sportivi Loria.gpx', '2025 Gran Premio Sportivi di Poggiana-Trofeo Bonin Costruzioni.gpx', '2025 Gran Premio del Perdono.gpx', '2025 Gran Premio della Liberazione Donne.gpx', '2025 Gran Premio della Liberazione.gpx', '2025 Grand Prix Antalya.gpx', '2025 Grand Prix Apollon Temple.gpx', '2025 Grand Prix Aspendos.gpx', '2025 Grand Prix Boqueron.gpx', '2025 Grand Prix Cerami.gpx', '2025 Grand Prix Ceratizit Women Junior.gpx', '2025 Grand Prix Chantal Biya Stage 1.gpx', '2025 Grand Prix Chantal Biya Stage 2.gpx', '2025 Grand Prix Chantal Biya Stage 3.gpx', '2025 Grand Prix Chantal Biya Stage 4.gpx', '2025 Grand Prix Chantal Biya Stage 5.gpx', '2025 Grand Prix Criquielion.gpx', '2025 Grand Prix Cycliste de Marseille La Marseillaise.gpx', '2025 Grand Prix Cycliste de Montreal.gpx', '2025 Grand Prix Cycliste de Quebec.gpx', '2025 Grand Prix Edebiyat Yolu.gpx', '2025 Grand Prix Feminin de Chambery.gpx', '2025 Grand Prix Herning.gpx', '2025 Grand Prix Kahramanmaras.gpx', '2025 Grand Prix Ordu.gpx', '2025 Grand Prix Presidente.gpx', '2025 Grand Prix Ruebliland Stage 1.gpx', '2025 Grand Prix Ruebliland Stage 2.gpx', '2025 Grand Prix Ruebliland Stage 3.gpx', '2025 Grand Prix Sakiat Sidi Youcef.gpx', '2025 Grand Prix Sonatrach.gpx', '2025 Grand Prix Surf City.gpx', '2025 Grand Prix Valromey Tour Feminin II.gpx', '2025 Grand Prix Valromey Tour Feminin.gpx', '2025 Grand Prix West Bohemia Stage 1.gpx', '2025 Grand Prix West Bohemia Stage 2.gpx', "2025 Grand Prix d'Isbergues - Pas de Calais.gpx", '2025 Grand Prix de Cotonou.gpx', '2025 Grand Prix de Denain - Porte du Hainaut.gpx', '2025 Grand Prix de Luxembourg.gpx', '2025 Grand Prix de Plouay.gpx', '2025 Grand Prix de Wallonie Dames.gpx', '2025 Grand Prix de Wallonie.gpx', '2025 Grand Prix de la Somme Conseil Departemental 80.gpx', "2025 Grand Prix de la Ville d'Alger.gpx", '2025 Grand Prix de la Ville de Lillers - Souvenir Bruno Comini.gpx', '2025 Grand Prix de la ville de Perenchies.gpx', '2025 Grand Prix du Morbihan Femmes.gpx', '2025 Grand Prix du Morbihan.gpx', '2025 Grand Prix el Salvador.gpx', '2025 Grande Premio Internacional Beiras e Serra da Estrela Stage 1.gpx', '2025 Grande Premio Internacional Beiras e Serra da Estrela Stage 2.gpx', '2025 Grande Premio Internacional Beiras e Serra da Estrela Stage 3.gpx', '2025 Gree - Tour of Guangxi Stage 1.gpx', '2025 Gree - Tour of Guangxi Stage 2.gpx', '2025 Gree - Tour of Guangxi Stage 3.gpx', '2025 Gree - Tour of Guangxi Stage 4.gpx', '2025 Gree - Tour of Guangxi Stage 5.gpx', '2025 Gree - Tour of Guangxi Stage 6.gpx', '2025 Grosser Preis des Kantons Aargau.gpx', '2025 Grote Prijs CHW Beveren.gpx', '2025 Grote Prijs Yvonne Reynders.gpx', '2025 Grote prijs Jean - Pierre Monsere.gpx', '2025 Guido Reybrouck Classic Stage 1.gpx', '2025 Guido Reybrouck Classic Stage 2.gpx', '2025 Hellenic Road National Championships - ITT.gpx', '2025 Hellenic Road National Championships.gpx', '2025 Heylen Vastgoed Heistse Pijl.gpx', '2025 IXINA Classic - Grote Prijs van de Stad Halle.gpx', "2025 Il Giro d'Abruzzo Stage 1.gpx", "2025 Il Giro d'Abruzzo Stage 2.gpx", "2025 Il Giro d'Abruzzo Stage 3.gpx", "2025 Il Giro d'Abruzzo Stage 4.gpx", '2025 Il Lombardia Under 23.gpx', '2025 Il Lombardia.gpx', '2025 International Rhodes GP.gpx', '2025 Internationale Cottbuser Junioren-Etappenfahrt Stage 1.gpx', '2025 Internationale Cottbuser Junioren-Etappenfahrt Stage 2-1.gpx', '2025 Internationale Cottbuser Junioren-Etappenfahrt Stage 2-2.gpx', '2025 Internationale Cottbuser Junioren-Etappenfahrt Stage 3.gpx', '2025 Irish Road National Championship - ITT.gpx', '2025 Irish Road National Championship.gpx', '2025 Israeli Road National Championships - ITT.gpx', '2025 Istarsko Proljece - Istrian Spring Trophy Prologue.gpx', '2025 Istarsko Proljece - Istrian Spring Trophy Stage 1.gpx', '2025 Istarsko Proljece - Istrian Spring Trophy Stage 2.gpx', '2025 Istarsko Proljece - Istrian Spring Trophy Stage 3.gpx', '2025 Italian Road National Championship - ITT.gpx', '2025 Italian Road National Championship.gpx', '2025 Itzulia Basque Country Stage 1.gpx', '2025 Itzulia Basque Country Stage 2.gpx', '2025 Itzulia Basque Country Stage 3.gpx', '2025 Itzulia Basque Country Stage 4.gpx', '2025 Itzulia Basque Country Stage 5.gpx', '2025 Itzulia Basque Country Stage 6.gpx', '2025 Itzulia Women Stage 1.gpx', '2025 Itzulia Women Stage 2.gpx', '2025 Itzulia Women 

In [29]:
import os

gpx_dir = "/Users/arthurdeletang/Desktop/Stage M1/Code/data/gpx_files_2"
corrompus = []

for fname in os.listdir(gpx_dir):
    if not fname.endswith('.gpx'):
        continue
    path = os.path.join(gpx_dir, fname)
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        debut = f.read(200)
    if '<!DOCTYPE' in debut or '<html' in debut or 'Bad gateway' in debut:
        corrompus.append(fname)

print(f"{len(corrompus)} fichiers corrompus")
for f in sorted(corrompus):
    print(f)

124 fichiers corrompus
2017 Giro d'Italia Rest day.gpx
2017 Koga Slag om Norg Rest day.gpx
2017 Tour de France Rest day.gpx
2017 Tour de l'Avenir Rest day.gpx
2017 Volta a Portugal em Bicicleta Santander Totta Rest day.gpx
2017 Vuelta a Espana Rest day.gpx
2018 Africa Cup - ITT.gpx
2018 Africa Cup - TTT.gpx
2018 Africa Cup.gpx
2018 Burmese Road National Championships - ITT.gpx
2018 Burmese Road National Championships.gpx
2018 Giro d'Italia Rest day.gpx
2018 Qatar Road National Championships.gpx
2018 Tour de France Rest day.gpx
2018 Tour de l'Espoir Rest day.gpx
2018 Tour of China II Rest day.gpx
2018 Tour of Fuzhou Stage 4.gpx
2018 Volta a Portugal em Bicicleta Santander Totta Rest day.gpx
2018 Vuelta Ciclista a la Provincia de San Juan Rest day.gpx
2018 Vuelta a Espana Rest day.gpx
2019 Belizean Road National Championships.gpx
2019 COPACI Campeonato Panamericano de Ruta Junior - ITT.gpx
2019 Chinese Road National Championships - TTT.gpx
2019 Chinese Road National Championships.gpx
2019 Cuban Road National Championships.gpx
2019 Cyprus Road National Championships - ITT.gpx
2019 Cyprus Road National Championships.gpx
2019 Dominican Road National Championships.gpx
2019 Georgian Road National Championships.gpx
2019 Giro Ciclistico d'Italia Rest day.gpx
2019 Giro d'Italia Rest day.gpx
2019 Hongkonger Road National Championships - ITT.gpx
2019 Jamaican Road National Championships - ITT.gpx
2019 Kazakhstani Road National Championships.gpx
2019 Marocaine Road National Championships - ITT.gpx
2019 Mauritian Road National Championships.gpx
2019 North Macedonian Road National Championships - ITT.gpx
2019 Philippinian Road National Championships - ITT.gpx
2019 Saint Vincentian Road National Championships - ITT.gpx
2019 Tour de France Rest day.gpx
2019 Tour de l'Avenir Rest day.gpx
2019 Tour de l'Espoir Rest day.gpx
2019 Tour of China II Rest day.gpx
2019 Tunisian Road National Championships - ITT.gpx
2019 Tunisian Road National Championships.gpx
2019 UAE Road Cycling Championships - ITT.gpx
2019 UAE Road Cycling Championships.gpx
2019 Virgin Islands Road National Championships - ITT.gpx
2019 Virgin Islands Road National Championships.gpx
2019 Volta a Portugal Santander Rest day.gpx
2019 Vuelta a Espana Rest day.gpx
2019 Vuelta a San Juan Internacional Rest day.gpx
2020 Albanian Road National Championships - ITT.gpx
2020 Albanian Road National Championships.gpx
2020 Brasilian Road National Championships - ITT.gpx
2020 Brasilian Road National Championships.gpx
2020 Chinese Road National Championships.gpx
2020 Cuban Road National Championships.gpx
2020 Cyprus Road National Championships - ITT.gpx
2020 Cyprus Road National Championships.gpx
2020 Dominican Road National Championships.gpx
2020 Giro d'Italia Rest day.gpx
2020 Kosovian Road National Championships - ITT.gpx
2020 North Macedonian Road National Championships - ITT.gpx
2020 Saint Vincentian Road National Championships - ITT.gpx
2020 Saint Vincentian Road National Championships.gpx
2020 Tour de France Rest day.gpx
2020 Tunisian Road National Championships - ITT.gpx
2020 Tunisian Road National Championships.gpx
2020 Vuelta Ciclista a la Provincia de San Juan Rest day.gpx
2020 Vuelta a Espana Rest day.gpx
2021 61th Craft Ster van Zwolle.gpx
2021 82^ Volta a Portugal em Bicicleta Santander Rest day.gpx
2021 Giro d'Italia Rest day.gpx
2021 La Vuelta ciclista a Espana Rest day.gpx
2021 Ronde van Limburg.gpx
2021 Tour de France Rest day.gpx
2022 CAC African Road Championships - ITT.gpx
2022 CAC African Road Championships - TTT.gpx
2022 Circuit des Ardennes Rest day.gpx
2022 Giro d'Italia Donne Rest day.gpx
2022 Giro d'Italia Giovani Under 23 Rest day.gpx
2022 Giro d'Italia Rest day.gpx
2022 Grand Prix Chantal Biya Rest day.gpx
2022 La Vuelta ciclista a Espana Rest day.gpx
2022 National Road Championships - United Arab Emirates - ITT.gpx
2022 Tour de France Rest day.gpx
2022 Tour de l'Avenir Rest day.gpx
2022 Volta a Portugal em Bicicleta Rest day.gpx
2023 Belgrade GP Woman Tour.gpx
2023 Giro d'Italia Donne.gpx
2023 Giro d'Italia Rest day.gpx
2023 Grand Prix El Marsa.gpx
2023 Junioren Rundfahrt.gpx
2023 La Vuelta Ciclista a Espana Rest day.gpx
2023 Ocean Cup China PingTan International Road Cycling Race.gpx
2023 Tour de France Rest day.gpx
2023 Tour du Pays de Montbeliard.gpx
2023 Volta a Portugal em Bicicleta Rest day.gpx
2023 Vuelta a San Juan Internacional Rest day.gpx
2024 Eroica Juniores - Nations' Cup Rest day.gpx
2024 Giro d'Italia Rest day.gpx
2024 Kreiz Breizh Elites Stage 2.gpx
2024 La Vuelta Ciclista a Espana Rest day.gpx
2024 Rutland-Melton CiCLE Classic.gpx
2024 Tour de France Rest day.gpx
2024 Tour du Maroc.gpx
2024 Tour of Austria.gpx
2024 Tour of Oman Stage 4.gpx
2024 Tour of Oman Stage 5.gpx
2024 Tour of Sharjah Rest day.gpx
2024 Tre Valli Varesine.gpx
2024 Volta a Portugal em Bicicleta Rest day.gpx
2025 Giro d'Italia Rest day.gpx
2025 Giro della Regione Friuli Venezia Giulia.gpx
2025 La Vuelta Ciclista a Espana.gpx
2025 NIBC Tour of Holland.gpx
2025 Tour Cycliste Feminin International de l'Ardeche.gpx
2025 Tour de France Rest day.gpx
2025 Tour de l'Avenir Femmes Rest day.gpx
2025 Tour du Rwanda.gpx
2025 Tour of Poyang Lake Rest day.gpx
2025 Volta a Portugal em Bicicleta Continente Rest day.gpx
2025 Vuelta Junior a la Ribera del Duero.gpx